import test from 'node:test'; import assert from 'node:assert/strict';
import { calculateLeadScore, dataCompleteness, duplicateStatus, isDuplicate, parseDiscoveryCsv, prepareImport, scoreDetails, type DiscoveryInput } from './core.ts';
const company = (overrides: Partial<DiscoveryInput> = {}): DiscoveryInput => ({ companyName:'مصنع الخليج',companyType:'مصنع',sector:'صناعي',city:'الدمام',website:'https://gulf.example',generalPhone:'0131234567',generalEmail:'info@gulf.example',contactName:'',contactPosition:'',linkedIn:'',discoverySource:'CSV',sourceUrl:'',notes:'مشروع توسع',projectSignal:true,...overrides });
test('scores a relevant Eastern Province lead highly',()=>assert.equal(calculateLeadScore(company()),100));
test('detects duplicates by normalized name, website, or phone',()=>{assert.ok(isDuplicate(company(),company({website:'',generalPhone:'',companyName:'مصنع  الخليج'})));assert.ok(isDuplicate(company(),company({companyName:'آخر',website:'https://www.gulf.example/'})));assert.ok(isDuplicate(company(),company({companyName:'آخر',website:'',generalPhone:'+966 13 123 4567'})));});
test('parses Arabic/English CSV rows',()=>{const rows=parseDiscoveryCsv('companyName,companyType,city,phone\n"شركة ألف",مقاول,الخبر,0500000000');assert.equal(rows.length,1);assert.equal(rows[0].companyName,'شركة ألف');assert.equal(rows[0].city,'الخبر');});
test('reports accepted, duplicate, review, and rejected import rows',()=>{const report=prepareImport([company(),company({companyName:'مصنع  الخليج'}),company({companyName:'بدون اتصال',website:'',generalPhone:'',generalEmail:''}),company({companyName:'ناقص',city:''})],[]);assert.equal(report.total,4);assert.equal(report.accepted.length,2);assert.equal(report.duplicates,1);assert.equal(report.needsReview,1);assert.equal(report.rejected,1);});
test('flags similar same-city names as possible duplicates',()=>assert.equal(duplicateStatus(company({companyName:'شركة الشرق للمقاولات',website:'',generalPhone:'',generalEmail:''}),company({companyName:'الشرق للمقاولات والتجارة',website:'',generalPhone:'',generalEmail:''})),'Possible Duplicate'));
test('explains scoring and computes data completeness',()=>{const details=scoreDetails(company());assert.equal(details.score,100);assert.ok(details.reasons.length>=3);assert.ok(dataCompleteness(company())>=60);});
