'use client';
import Link from'next/link';
import {useEffect,useMemo,useState}from'react';
import {CRMPage}from'./crm-shell';
import {simpleCrud,type SimpleRow}from'../lib/supabase/simple-crud';
import {rankAcquisitionProjects,signalPriority,funnelCounts,routeReason}from'../lib/acquisition-os/core';
import {ROUTE_LABELS,type RevenueRoute}from'../lib/project-capture/core';

const s=(v:unknown)=>String(v??'').trim();
const n=(v:unknown)=>Number(v||0)||0;

export function AcquisitionCommandCenter(){
 const[data,setData]=useState<Record<string,SimpleRow[]>>({});
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const specs:[string,number,string][]=[
  ['projects',500,'updated_at'],['project_entities',1500,'updated_at'],['project_packages',1500,'updated_at'],['project_access_paths',1500,'updated_at'],
  ['external_signals',1000,'detected_at'],['raw_market_events',1500,'detected_at'],['market_radar_runs',100,'started_at'],['companies',1000,'lead_score'],['meetings',500,'meeting_date'],['opportunities',500,'updated_at']
 ];const rows=await Promise.all(specs.map(async([table,size,order])=>[table,(await simpleCrud.page(table,1,size,{order})).rows]as const));setData(Object.fromEntries(rows))}catch(e){setError(e instanceof Error?e.message:'تعذر تجهيز مركز الاستقطاب.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const projects=data.projects??[],entities=data.project_entities??[],packages=data.project_packages??[],paths=data.project_access_paths??[],signals=data.external_signals??[],marketEvents=data.raw_market_events??[],marketRuns=data.market_radar_runs??[],companies=data.companies??[],meetings=data.meetings??[],opps=data.opportunities??[];
 const companyById=useMemo(()=>new Map(companies.map(c=>[s(c.id),c])),[companies]);
 const ranked=useMemo(()=>rankAcquisitionProjects(projects,entities,packages,paths),[projects,entities,packages,paths]);
 const linkedSignalIds=useMemo(()=>new Set(projects.map(p=>s(p.source_signal_id)).filter(Boolean)),[projects]);
 const radar=useMemo(()=>signals.filter(x=>!linkedSignalIds.has(s(x.id))).map(x=>({signal:x,score:signalPriority(x)})).sort((a,b)=>b.score-a.score).slice(0,8),[signals,linkedSignalIds]);
 const funnel=useMemo(()=>funnelCounts(projects,meetings,opps),[projects,meetings,opps]);
 const focus=ranked[0];
 const marketNew=marketEvents.filter(x=>s(x.review_status)==='NEW').length;
 const marketVerified=marketEvents.filter(x=>s(x.verification_status)==='verified').length;
 const latestMarketRun=[...marketRuns].sort((a,b)=>s(b.started_at).localeCompare(s(a.started_at)))[0];
 const createCandidate=async(signal:SimpleRow)=>{if(s(signal.verification_status)!=='verified'){setError('الإشارة غير معتمدة بشريًا بعد.');return}try{const company=companyById.get(s(signal.company_id));const p=await simpleCrud.create('projects',{project_name:s(signal.title)||`Project Candidate — ${s(company?.company_name)}`,owner_company_id:s(signal.company_id)||null,source_signal_id:signal.id,project_type:s(signal.signal_type)||'UNCLASSIFIED',sector:s(company?.sector),city:s(company?.city),stage:'CANDIDATE',route_to_revenue:'UNDEFINED',verification_status:'needs_research',verification_confidence:0,source_url:s(signal.source_url),why_now:s(signal.summary)||s(signal.title),last_signal_at:s(signal.date_found)||s(signal.found_at)||new Date().toISOString(),next_action:'تحقق من المشروع وحدد Owner / Consultant / Main Contractor'});if(signal.company_id)await simpleCrud.create('project_entities',{project_id:p.id,company_id:signal.company_id,entity_name:s(company?.company_name),entity_role:'OWNER',status:'IDENTIFIED',source_url:s(signal.source_url),verification_status:'needs_research',verification_confidence:0});setNotice('تم تحويل الإشارة إلى Project Candidate دون اعتماد تلقائي للمشروع.');await load()}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء Project Candidate.')}};
 return <CRMPage title="مركز الاستقطاب" description="من السوق إلى المشروع ثم إلى أقصر طريق للوصول وRFQ — هذه هي شاشة التشغيل الرئيسية لـ ALGAEU.">
  {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
  <section className="grid gap-3 md:grid-cols-7">
   {[['Saudi Signals',marketNew],['Qualified Projects',funnel.qualified],['Access Found',funnel.access],['Meetings',funnel.meetings],['RFQ / Bid',funnel.rfq],['Won',funnel.won],['Verified Signals',marketVerified]].map(([label,value])=><div key={String(label)} className="crm-kpi"><span>{label}</span><b className="mt-2 block text-3xl">{value}</b></div>)}
  </section>
  <section className="crm-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-[#8c7cff]">SAUDI MARKET RADAR</p><h3 className="text-xl font-bold">السوق قبل أن يصبح RFQ</h3><p className="mt-1 text-xs text-[#8f96a3]">آخر تشغيل: {latestMarketRun?s(latestMarketRun.status):'لم يُشغّل بعد'} · {latestMarketRun?`${Number(latestMarketRun.events_inserted||0)} إشارات جديدة`:''}</p></div><Link href="/market-intelligence" className="btn-primary">فتح Saudi Market Intelligence</Link></div></section>
  {loading?<div className="crm-empty">جارٍ بناء صورة السوق…</div>:<>
   {focus?<section className="crm-card overflow-hidden border-2 border-[#6f5cff]"><header className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><p className="text-xs font-bold text-[#8c7cff]">أفضل فرصة للعمل الآن</p><h3 className="mt-1 text-2xl font-black">{s(focus.project.project_name)}</h3><p className="mt-1 text-sm text-[#8f96a3]">{focus.whyNow}</p></div><div className="text-left"><span className="text-xs text-[#8f96a3]">Capture Score</span><b className="block text-4xl">{focus.score}</b></div></header><div className="grid gap-4 p-5 lg:grid-cols-4"><div><span className="text-xs text-[#8f96a3]">Route-to-Revenue</span><b className="block">{ROUTE_LABELS[s(focus.project.route_to_revenue) as RevenueRoute]||'غير محدد'}</b><p className="mt-1 text-xs text-[#8f96a3]">{routeReason(focus.project.route_to_revenue)}</p></div><div><span className="text-xs text-[#8f96a3]">خريطة المشروع</span><b className="block text-xl">{focus.coverage.known}/{focus.coverage.total}</b><p className="text-xs text-[#8f96a3]">Owner / Consultant / Main Contractor</p></div><div><span className="text-xs text-[#8f96a3]">قوة الوصول</span><b className="block text-xl">{focus.access}/100</b><p className="text-xs text-[#8f96a3]">أفضل Access Path</p></div><div><span className="text-xs text-[#8f96a3]">أفضل حزمة</span><b className="block text-xl">{focus.packageFit}%</b><p className="text-xs text-[#8f96a3]">Scope Fit</p></div></div><div className="flex flex-wrap items-center justify-between gap-3 border-t p-4"><div><span className="text-xs text-[#8f96a3]">NEXT MOVE</span><b className="mr-2">{focus.move.label}</b></div><Link href={`/projects/${focus.project.id}`} className="btn-primary">فتح غرفة المطاردة</Link></div></section>:<div className="crm-empty">لا يوجد Project Pursuit نشط بعد. ابدأ من Project Radar.</div>}
   <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
    <section className="crm-card p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#8c7cff]">PROJECT RADAR</p><h3 className="text-xl font-bold">إشارات لم تتحول إلى مشروع بعد</h3></div><Link href="/radar" className="btn-ghost">فتح الرادار</Link></div><div className="mt-4 space-y-2">{radar.map(({signal,score})=><article key={signal.id} className="rounded-2xl border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex gap-2"><span className={`crm-chip ${s(signal.verification_status)==='verified'?'status-success':'status-warning'}`}>{s(signal.verification_status)==='verified'?'Signal موثق':'يحتاج مراجعة'}</span><span className="crm-chip status-neutral">Radar {score}</span></div><b className="mt-2 block">{s(signal.title)||s(signal.signal_type)||'إشارة غير مسماة'}</b><p className="mt-1 text-xs text-[#8f96a3]">{s(companyById.get(s(signal.company_id))?.company_name)||'شركة غير مرتبطة'} · {s(signal.date_found)||s(signal.found_at)||'تاريخ غير محدد'}</p></div><div className="flex gap-2">{s(signal.source_url)&&<a href={s(signal.source_url)} target="_blank" rel="noreferrer" className="btn-ghost">المصدر</a>}<button disabled={s(signal.verification_status)!=='verified'} onClick={()=>void createCandidate(signal)} className="btn-secondary disabled:opacity-40">إنشاء Project Candidate</button></div></div></article>)}{!radar.length&&<div className="crm-empty">لا توجد إشارات غير مربوطة حاليًا.</div>}</div></section>
    <section className="crm-card p-4"><p className="text-xs font-bold text-[#ff9d5c]">PURSUE BOARD</p><h3 className="text-xl font-bold">أعلى المشاريع التي تحتاج حركة</h3><div className="mt-4 space-y-3">{ranked.slice(0,6).map((x,i)=><Link key={x.project.id} href={`/projects/${x.project.id}`} className="block rounded-2xl border p-3"><div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-[#2d3040] font-black">{i+1}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><b>{s(x.project.project_name)}</b><span className="crm-chip status-neutral">{x.score}</span></div><p className="mt-1 text-xs text-[#8f96a3]">{x.move.label}</p><div className="mt-2 flex flex-wrap gap-2 text-xs"><span>Map {x.coverage.known}/{x.coverage.total}</span><span>Access {x.access}</span><span>Fit {x.packageFit}</span></div></div></div></Link>)}{!ranked.length&&<div className="crm-empty">لا توجد Pursuits حتى الآن.</div>}</div></section>
   </div>
  </>}
 </CRMPage>
}
