'use client';
import {useEffect,useMemo,useState}from'react';
import Link from'next/link';
import {CRMPage}from'./crm-shell';
import {simpleCrud,type SimpleRow}from'../lib/supabase/simple-crud';
import {dueState}from'../lib/acquisition-v3/core';
const s=(v:unknown)=>String(v??'').trim();
const dt=(v:unknown)=>{const x=s(v);return x?new Date(x).toLocaleString('ar-SA'):'—'};

export function BidBoardV3(){
 const[data,setData]=useState<Record<string,SimpleRow[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[form,setForm]=useState({project_id:'',package_id:'',invite_source:'',received_at:'',job_walk_at:'',due_at:'',status:'INVITED',responsible_person:'',bid_value:''});
 useEffect(()=>{void(async()=>{try{const specs:[string,number,string][]=[['bid_board_items',2500,'due_at'],['projects',1500,'updated_at'],['project_packages',3000,'updated_at']];const rows=await Promise.all(specs.map(async([t,z,o])=>[t,(await simpleCrud.page(t,1,z,{order:o})).rows]as const));setData(Object.fromEntries(rows))}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل Bid Board.')}finally{setLoading(false)}})()},[]);
 const items=data.bid_board_items??[],projects=data.projects??[],packages=data.project_packages??[];
 const projectById=useMemo(()=>new Map(projects.map(x=>[s(x.id),x])),[projects]),packageById=useMemo(()=>new Map(packages.map(x=>[s(x.id),x])),[packages]);
 const rows=useMemo(()=>[...items].sort((a,b)=>{const rank:Record<string,number>={OVERDUE:0,DUE_SOON:1,UPCOMING:2,NO_DUE:3};return rank[dueState(a.due_at)]-rank[dueState(b.due_at)]||s(a.due_at).localeCompare(s(b.due_at))}),[items]);
 const groups=['OVERDUE','DUE_SOON','UPCOMING','NO_DUE'];
 const addBid=async()=>{if(!form.project_id){setError('حدد المشروع.');return}try{await simpleCrud.create('bid_board_items',{...form,package_id:form.package_id||null,received_at:form.received_at||null,job_walk_at:form.job_walk_at||null,due_at:form.due_at||null,bid_value:form.bid_value?Number(form.bid_value):null});setNotice('تمت إضافة Bid Invite إلى اللوحة.');setForm({project_id:'',package_id:'',invite_source:'',received_at:'',job_walk_at:'',due_at:'',status:'INVITED',responsible_person:'',bid_value:''});const r=await simpleCrud.page('bid_board_items',1,2500,{order:'due_at'});setData(v=>({...v,bid_board_items:r.rows}))}catch(e){setError(e instanceof Error?e.message:'تعذر إضافة Bid Invite.')}};

 return <CRMPage title="Bid Board" description="لوحة واحدة لكل Bid Invite وRFQ وموعد تسليم ومسؤول، حتى لا تضيع الفرص بين البريد والملفات.">
  {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
  <section className="grid gap-3 md:grid-cols-4">{groups.map(g=><div className="crm-kpi" key={g}><span>{g}</span><b className="mt-2 block text-3xl">{items.filter(x=>dueState(x.due_at)===g).length}</b></div>)}</section>  <section className="crm-card p-4"><div><p className="text-xs font-bold text-[var(--nav-accent)]">NEW BID INVITE</p><h3 className="font-bold">أدخل RFQ / Bid Invite فور وصوله</h3></div><div className="mt-3 grid gap-2 md:grid-cols-4"><select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value,package_id:''})} className="rounded-xl border p-2"><option value="">المشروع...</option>{projects.map(x=><option value={s(x.id)} key={x.id}>{s(x.project_name)}</option>)}</select><select value={form.package_id} onChange={e=>setForm({...form,package_id:e.target.value})} className="rounded-xl border p-2"><option value="">الحزمة (اختياري)</option>{packages.filter(x=>!form.project_id||s(x.project_id)===form.project_id).map(x=><option value={s(x.id)} key={x.id}>{s(x.package_name)}</option>)}</select><input value={form.invite_source} onChange={e=>setForm({...form,invite_source:e.target.value})} placeholder="مصدر الدعوة" className="rounded-xl border p-2"/><input value={form.responsible_person} onChange={e=>setForm({...form,responsible_person:e.target.value})} placeholder="المسؤول" className="rounded-xl border p-2"/><label className="text-xs">Received<input type="datetime-local" value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})} className="mt-1 w-full rounded-xl border p-2"/></label><label className="text-xs">Job Walk<input type="datetime-local" value={form.job_walk_at} onChange={e=>setForm({...form,job_walk_at:e.target.value})} className="mt-1 w-full rounded-xl border p-2"/></label><label className="text-xs">Due<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})} className="mt-1 w-full rounded-xl border p-2"/></label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border p-2"><option>INVITED</option><option>REVIEWING</option><option>NO_BID</option><option>BIDDING</option><option>SUBMITTED</option><option>CLARIFICATION</option><option>AWARDED</option><option>LOST</option></select></div><button onClick={()=>void addBid()} className="btn-secondary mt-3">إضافة إلى Bid Board</button></section>
  {loading?<div className="crm-empty">جارٍ تحميل Bid Board…</div>:<div className="grid gap-3">{rows.map(item=>{const project=projectById.get(s(item.project_id)),pack=packageById.get(s(item.package_id)),due=dueState(item.due_at);return <article className="crm-card p-4" key={item.id}><div className="grid gap-4 lg:grid-cols-[1.4fr_.65fr_.75fr_.75fr_auto] lg:items-center"><div><div className="flex gap-2"><span className={`crm-chip ${due==='OVERDUE'?'status-danger':due==='DUE_SOON'?'status-warning':'status-neutral'}`}>{due}</span><span className="crm-chip status-neutral">{s(item.status)}</span></div><h3 className="mt-2 text-lg font-bold">{s(project?.project_name)||'مشروع غير معروف'}</h3><p className="mt-1 text-xs text-[#8f96a3]">{s(pack?.package_name)||'الحزمة غير محددة'} · {s(item.invite_source)||'مصدر الدعوة غير مسجل'}</p></div><div><span className="text-xs text-[#8f96a3]">Due</span><b className="block">{dt(item.due_at)}</b></div><div><span className="text-xs text-[#8f96a3]">Job Walk</span><b className="block">{dt(item.job_walk_at)}</b></div><div><span className="text-xs text-[#8f96a3]">Responsible</span><b className="block">{s(item.responsible_person)||'غير معين'}</b></div><div>{project&&<Link href={`/projects/${project.id}`} className="btn-primary">فتح Pursuit</Link>}</div></div></article>})}{!rows.length&&<div className="crm-empty">لا توجد Bid Invites مسجلة بعد.</div>}</div>}
 </CRMPage>
}
