'use client';
import { useEffect, useMemo, useState } from 'react';
import { discoveryCsvTemplate, parseDiscoveryCsv, safeText, scoreDetails, dataCompleteness, type DiscoveryInput, type DiscoveryStatus } from '../lib/discovery/core';
import { discoveryService, type DiscoveredCompany } from '../lib/discovery/service';

const empty: DiscoveryInput = { companyName: '', companyType: 'مصنع', sector: '', activity:'',address:'',tags:'', city: 'الدمام', website: '', generalPhone: '', generalEmail: '', contactName: '', contactPosition: '',contactEmail:'',contactPhone:'', linkedIn: '', discoverySource: 'إدخال داخلي', sourceUrl: '', notes: '', projectSignal: false, verificationStatus: 'بحاجة تحقق' };
const statuses: DiscoveryStatus[] = ['جديد', 'بحاجة تحقق', 'مؤهل', 'غير مناسب', 'تمت إضافته للـ CRM'];
const inputClass = 'rounded-xl border border-[#decda8] bg-white px-3 py-2 text-sm outline-none focus:border-[#8a6f35]';

export function CompanyDiscoveryWorkspace() {
  const [items, setItems] = useState<DiscoveredCompany[]>([]); const [selected, setSelected] = useState<string[]>([]);
  const [form, setForm] = useState<DiscoveryInput>(empty); const [editing, setEditing] = useState<DiscoveredCompany | null>(null);
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [report, setReport] = useState<{total:number; imported:number; added?:number; duplicates:number; possibleDuplicates?:number; possibleRemaining?:number; approvalFailures?:number; needsReview:number; rejected:number}|null>(null);
  const [pendingRows,setPendingRows]=useState<DiscoveryInput[]>([]); const [preview,setPreview]=useState<Awaited<ReturnType<typeof discoveryService.preview>>|null>(null);
  const [search,setSearch]=useState(''); const [statusFilter,setStatusFilter]=useState('الكل'); const [cityFilter,setCityFilter]=useState('الكل'); const [paste,setPaste]=useState(''); const [page,setPage]=useState(1);
  const load = async () => { setLoading(true); try { setItems(await discoveryService.list()); setError(''); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => [...items].filter(item=>(statusFilter==='الكل'||safeText(item.reviewStatus)===statusFilter)&&(cityFilter==='الكل'||safeText(item.city)===cityFilter)&&`${safeText(item.companyName)} ${safeText(item.sector)} ${safeText(item.city)}`.toLowerCase().includes(safeText(search).toLowerCase())).sort((a, b) => Number(b.leadScore||0) - Number(a.leadScore||0)), [items,search,statusFilter,cityFilter]);
  const pageSize=10; const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const sorted=filtered.slice((page-1)*pageSize,page*pageSize);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(''); setMessage(''); try { await action(); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const importItems = (rows: DiscoveryInput[]) => run(async () => { const result = await discoveryService.import(rows); setReport(result); setPreview(null);setPendingRows([]);setMessage(`اكتملت المعالجة: أضيف ${result.added} New Lead إلى Companies، واستُبعد ${result.duplicates} Exact Duplicate، وبقي ${result.possibleRemaining} للمراجعة اليدوية.${result.approvalFailures?` تعذر اعتماد ${result.approvalFailures} سجل.`:''}`); setForm(empty); });
  const previewImport = (rows:DiscoveryInput[])=>run(async()=>{const result=await discoveryService.preview(rows);setPendingRows(rows);setPreview(result);setMessage('تم تحليل الملف. راجع النتيجة ثم أكد الحفظ.');});
  const downloadTemplate = () => { const url=URL.createObjectURL(new Blob([discoveryCsvTemplate],{type:'text/csv;charset=utf-8'})); const link=document.createElement('a');link.href=url;link.download='algaeu-company-discovery-template.csv';link.click();URL.revokeObjectURL(url); };
  const approveRows = (rows:DiscoveredCompany[]) => run(async () => { const eligible=rows.filter(row=>row.reviewStatus!=='تمت إضافته للـ CRM');const results=await Promise.allSettled(eligible.map(item=>discoveryService.approve(item)));const succeeded=results.filter(result=>result.status==='fulfilled').length;const failed=results.length-succeeded;setMessage(`تم اعتماد ${succeeded} شركة وإضافتها إلى CRM.${failed?` تعذر اعتماد ${failed} شركة؛ راجع التكرار أو البيانات.`:''}`);setSelected([]); });
  const approveSelected = () => approveRows(items.filter(row=>selected.includes(row.id)));
  return <div className="space-y-5">
    {error && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message && <div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
    {report && <section className="grid gap-2 sm:grid-cols-6">{[['الإجمالي',report.total],['أضيفت إلى Companies',report.added??0],['Exact مستبعدة',report.duplicates],['Possible للمراجعة',report.possibleRemaining??report.possibleDuplicates??0],['تحتاج مراجعة بيانات',report.needsReview],['مرفوضة لنقص البيانات',report.rejected]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[#ead9b3] bg-white p-3"><p className="text-xs text-[#6f6044]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>}
    {preview&&<section className="rounded-2xl border border-amber-300 bg-amber-50 p-4"><h3 className="font-semibold">معاينة الاستيراد قبل الحفظ</h3><div className="mt-3 grid gap-2 sm:grid-cols-5">{[['الإجمالي',preview.total],['صالحة للحفظ',preview.accepted.length],['مكررة',preview.duplicates],['تكرار محتمل',preview.possibleDuplicates],['مرفوضة',preview.rejected]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-white p-3"><p className="text-xs">{label}</p><strong className="text-xl">{value}</strong></div>)}</div>{preview.rejections.length>0&&<div className="mt-3 max-h-40 overflow-auto rounded-xl bg-white p-3 text-sm">{preview.rejections.map(row=><p key={row.rowNumber}>الصف {row.rowNumber} ({row.companyName}): {row.reasons.join('، ')}</p>)}</div>}<div className="mt-3 flex gap-2"><button disabled={!preview.accepted.length||busy} onClick={()=>void importItems(pendingRows)} className="rounded-xl bg-emerald-700 px-4 py-2 text-white disabled:opacity-40">تأكيد حفظ السجلات المقبولة</button><button onClick={()=>{setPreview(null);setPendingRows([])}} className="rounded-xl border bg-white px-4 py-2">إلغاء</button></div></section>}
    <section className="rounded-2xl border border-[#ead9b3] bg-[#fdf8ee] p-4"><h3 className="font-semibold">إضافة أو استيراد دفعة</h3><p className="mt-1 text-xs text-[#6f6044]">يدعم CSV بالأعمدة: companyName, companyType, sector, city, website, phone, email, source, sourceUrl, notes.</p>
      <div className="mt-3 grid gap-2 md:grid-cols-3">{(['companyName','companyType','sector','activity','city','address','website','generalPhone','generalEmail','contactName','contactPosition','contactEmail','contactPhone','linkedIn','tags','discoverySource','sourceUrl'] as const).map((key) => <input key={key} className={inputClass} value={form[key] as string} onChange={(e) => setForm({...form,[key]:e.target.value})} placeholder={({companyName:'اسم الشركة *',companyType:'الفئة *',sector:'القطاع',activity:'النشاط',city:'المدينة *',address:'العنوان',website:'الموقع الإلكتروني',generalPhone:'الهاتف العام',generalEmail:'البريد العام',contactName:'اسم مسؤول التواصل',contactPosition:'منصب مسؤول التواصل',contactEmail:'بريد المسؤول',contactPhone:'هاتف المسؤول',linkedIn:'LinkedIn',tags:'وسوم مفصولة بفاصلة',discoverySource:'مصدر البيانات',sourceUrl:'رابط المصدر'} as Record<string,string>)[key]} />)}
      <textarea className={`${inputClass} md:col-span-2`} value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.projectSignal} onChange={(e)=>setForm({...form,projectSignal:e.target.checked})}/> توجد مؤشرات مشاريع مستمرة</label></div>
      <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || !form.companyName} onClick={()=>void importItems([form])} className="rounded-xl bg-[#2f2417] px-4 py-2 text-sm text-white disabled:opacity-50">إضافة للمراجعة</button><label className="cursor-pointer rounded-xl border border-[#8a6f35] px-4 py-2 text-sm">استيراد CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={(e)=>{const file=e.target.files?.[0]; if(file) void file.text().then((text)=>previewImport(parseDiscoveryCsv(text))); e.target.value='';}}/></label><button type="button" onClick={downloadTemplate} className="rounded-xl border border-[#8a6f35] bg-white px-4 py-2 text-sm">تنزيل نموذج CSV فارغ</button></div>
      <details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">لصق بيانات CSV منظمة</summary><textarea value={paste} onChange={e=>setPaste(e.target.value)} className={`${inputClass} mt-2 min-h-28 w-full font-mono`} placeholder="الصق رؤوس CSV والصفوف هنا"/><button disabled={!paste.trim()||busy} onClick={()=>void previewImport(parseDiscoveryCsv(paste)).then(()=>setPaste(''))} className="mt-2 rounded-xl bg-[#6f6044] px-4 py-2 text-sm text-white disabled:opacity-40">تحليل ومعاينة</button></details>
    </section>
    <section className="rounded-2xl border border-[#ead9b3] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">شاشة المراجعة</h3><p className="text-xs text-[#6f6044]">مرتبة تلقائياً حسب Lead Score.</p></div><div className="flex flex-wrap gap-2"><button disabled={!selected.length||busy} onClick={()=>void approveSelected()} className="rounded-xl bg-emerald-700 px-3 py-2 text-sm text-white disabled:opacity-40">اعتماد المحدد</button><button disabled={!filtered.some(row=>row.reviewStatus!=='تمت إضافته للـ CRM')||busy} onClick={()=>void approveRows(filtered)} className="rounded-xl bg-[#2f2417] px-3 py-2 text-sm text-white disabled:opacity-40">اعتماد الكل</button><button disabled={!selected.length||busy} onClick={()=>void run(async()=>{await discoveryService.reject(selected);setSelected([]);setMessage('تم رفض السجلات المحددة.');})} className="rounded-xl bg-red-700 px-3 py-2 text-sm text-white disabled:opacity-40">رفض المحدد</button></div></div>
      <div className="mt-3 grid gap-2 sm:grid-cols-3"><input className={inputClass} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="بحث بالاسم أو القطاع أو المدينة"/><select className={inputClass} value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1)}}><option>الكل</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select className={inputClass} value={cityFilter} onChange={e=>{setCityFilter(e.target.value);setPage(1)}}><option>الكل</option>{[...new Set(items.map(i=>i.city).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select></div>
      {loading ? <p className="py-8 text-center text-sm">جارٍ التحميل...</p> : !sorted.length ? <p className="py-8 text-center text-sm text-[#6f6044]">لا توجد شركات تطابق البحث.</p> : <div className="mt-4 overflow-x-auto"><table className="min-w-full text-right text-sm"><thead><tr className="border-b">{['','الشركة','النوع/القطاع','المدينة','الاتصال','الحالة','الدرجة',''].map((h,i)=><th key={`${h}-${i}`} className="p-2">{h}</th>)}</tr></thead><tbody>{sorted.map((item)=>{const detail=scoreDetails(item);return <tr key={item.id} className="border-b align-top"><td className="p-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={(e)=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/></td><td className="p-2 font-semibold">{item.companyName}<div className="font-normal text-xs text-[#6f6044]">{item.discoverySource} · اكتمال {dataCompleteness(item)}%</div></td><td className="p-2">{item.companyType}<div className="text-xs">{item.sector}</div></td><td className="p-2">{item.city}</td><td className="p-2 text-xs">{item.generalPhone}<br/>{item.generalEmail}</td><td className="p-2">{item.reviewStatus}</td><td className="p-2 font-bold">{item.leadScore}/100<div className="mt-1 max-w-44 text-xs font-normal text-emerald-700">{detail.reasons.slice(0,2).map(r=><div key={r}>+ {r}</div>)}</div>{detail.missing.slice(0,1).map(r=><div key={r} className="text-xs font-normal text-red-600">- {r}</div>)}</td><td className="p-2"><button onClick={()=>setEditing(item)} className="text-[#8a6f35] underline">تعديل</button></td></tr>})}</tbody></table><div className="mt-3 flex items-center justify-between text-sm"><span>{filtered.length} نتيجة</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-1 disabled:opacity-30">السابق</button><span>{page}/{pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-1 disabled:opacity-30">التالي</button></div></div></div>}
    </section>
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={(e)=>{e.preventDefault();void run(async()=>{await discoveryService.update(editing.id,editing,editing.reviewStatus);setEditing(null);setMessage('تم حفظ التعديلات.');});}} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5"><h3 className="mb-4 font-semibold">تعديل الشركة المكتشفة</h3><div className="grid gap-2 md:grid-cols-2">{(['companyName','companyType','sector','city','website','generalPhone','generalEmail','contactName','contactPosition','linkedIn','discoverySource','sourceUrl','notes'] as const).map(key=><input key={key} className={inputClass} value={editing[key] as string} onChange={(e)=>setEditing({...editing,[key]:e.target.value})} placeholder={key}/>) }<select className={inputClass} value={editing.reviewStatus} onChange={(e)=>setEditing({...editing,reviewStatus:e.target.value as DiscoveryStatus})}>{statuses.map(status=><option key={status}>{status}</option>)}</select></div><div className="mt-4 flex gap-2"><button className="rounded-xl bg-[#2f2417] px-4 py-2 text-white">حفظ</button><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border px-4 py-2">إلغاء</button></div></form></div>}
  </div>;
}
