'use client';
import { useEffect, useMemo, useState } from 'react';
import { parseDiscoveryCsv, type DiscoveryInput, type DiscoveryStatus } from '../lib/discovery/core';
import { discoveryService, type DiscoveredCompany } from '../lib/discovery/service';

const empty: DiscoveryInput = { companyName: '', companyType: 'مصنع', sector: '', city: 'الدمام', website: '', generalPhone: '', generalEmail: '', discoverySource: 'إدخال داخلي', sourceUrl: '', notes: '', projectSignal: false, verificationStatus: 'بحاجة تحقق' };
const statuses: DiscoveryStatus[] = ['جديد', 'بحاجة تحقق', 'مؤهل', 'غير مناسب', 'تمت إضافته للـ CRM'];
const inputClass = 'rounded-xl border border-[#decda8] bg-white px-3 py-2 text-sm outline-none focus:border-[#8a6f35]';

export function CompanyDiscoveryWorkspace() {
  const [items, setItems] = useState<DiscoveredCompany[]>([]); const [selected, setSelected] = useState<string[]>([]);
  const [form, setForm] = useState<DiscoveryInput>(empty); const [editing, setEditing] = useState<DiscoveredCompany | null>(null);
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); try { setItems(await discoveryService.list()); setError(''); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const sorted = useMemo(() => [...items].sort((a, b) => b.leadScore - a.leadScore), [items]);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(''); setMessage(''); try { await action(); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const importItems = (rows: DiscoveryInput[]) => run(async () => { const result = await discoveryService.import(rows); setMessage(`تم استيراد ${result.imported} شركة، وتجاوز ${result.duplicates} سجل مكرر.`); setForm(empty); });
  const approveSelected = () => run(async () => { for (const item of items.filter((row) => selected.includes(row.id) && row.reviewStatus !== 'تمت إضافته للـ CRM')) await discoveryService.approve(item); setMessage(`تم اعتماد ${selected.length} شركة وإضافتها إلى CRM.`); setSelected([]); });
  return <div className="space-y-5">
    {error && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message && <div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
    <section className="rounded-2xl border border-[#ead9b3] bg-[#fdf8ee] p-4"><h3 className="font-semibold">إضافة أو استيراد دفعة</h3><p className="mt-1 text-xs text-[#6f6044]">يدعم CSV بالأعمدة: companyName, companyType, sector, city, website, phone, email, source, sourceUrl, notes.</p>
      <div className="mt-3 grid gap-2 md:grid-cols-3">{(['companyName','companyType','sector','city','website','generalPhone','generalEmail','discoverySource','sourceUrl'] as const).map((key) => <input key={key} className={inputClass} value={form[key] as string} onChange={(e) => setForm({...form,[key]:e.target.value})} placeholder={({companyName:'اسم الشركة',companyType:'النوع',sector:'القطاع',city:'المدينة',website:'الموقع الإلكتروني',generalPhone:'الهاتف',generalEmail:'البريد',discoverySource:'المصدر',sourceUrl:'رابط المصدر'} as Record<string,string>)[key]} />)}
      <textarea className={`${inputClass} md:col-span-2`} value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.projectSignal} onChange={(e)=>setForm({...form,projectSignal:e.target.checked})}/> توجد مؤشرات مشاريع مستمرة</label></div>
      <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || !form.companyName} onClick={()=>void importItems([form])} className="rounded-xl bg-[#2f2417] px-4 py-2 text-sm text-white disabled:opacity-50">إضافة للمراجعة</button><label className="cursor-pointer rounded-xl border border-[#8a6f35] px-4 py-2 text-sm">استيراد CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={(e)=>{const file=e.target.files?.[0]; if(file) void file.text().then((text)=>importItems(parseDiscoveryCsv(text))); e.target.value='';}}/></label></div>
    </section>
    <section className="rounded-2xl border border-[#ead9b3] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">شاشة المراجعة</h3><p className="text-xs text-[#6f6044]">مرتبة تلقائياً حسب Lead Score.</p></div><div className="flex gap-2"><button disabled={!selected.length||busy} onClick={()=>void approveSelected()} className="rounded-xl bg-emerald-700 px-3 py-2 text-sm text-white disabled:opacity-40">اعتماد المحدد</button><button disabled={!selected.length||busy} onClick={()=>void run(async()=>{await discoveryService.reject(selected);setSelected([]);setMessage('تم رفض السجلات المحددة.');})} className="rounded-xl bg-red-700 px-3 py-2 text-sm text-white disabled:opacity-40">رفض المحدد</button></div></div>
      {loading ? <p className="py-8 text-center text-sm">جارٍ التحميل...</p> : !sorted.length ? <p className="py-8 text-center text-sm text-[#6f6044]">لا توجد شركات قيد المراجعة.</p> : <div className="mt-4 overflow-x-auto"><table className="min-w-full text-right text-sm"><thead><tr className="border-b">{['','الشركة','النوع/القطاع','المدينة','الاتصال','الحالة','الدرجة',''].map((h,i)=><th key={`${h}-${i}`} className="p-2">{h}</th>)}</tr></thead><tbody>{sorted.map((item)=><tr key={item.id} className="border-b align-top"><td className="p-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={(e)=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/></td><td className="p-2 font-semibold">{item.companyName}<div className="font-normal text-xs text-[#6f6044]">{item.discoverySource}</div></td><td className="p-2">{item.companyType}<div className="text-xs">{item.sector}</div></td><td className="p-2">{item.city}</td><td className="p-2 text-xs">{item.generalPhone}<br/>{item.generalEmail}</td><td className="p-2">{item.reviewStatus}</td><td className="p-2 font-bold">{item.leadScore}/100</td><td className="p-2"><button onClick={()=>setEditing(item)} className="text-[#8a6f35] underline">تعديل</button></td></tr>)}</tbody></table></div>}
    </section>
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={(e)=>{e.preventDefault();void run(async()=>{await discoveryService.update(editing.id,editing,editing.reviewStatus);setEditing(null);setMessage('تم حفظ التعديلات.');});}} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5"><h3 className="mb-4 font-semibold">تعديل الشركة المكتشفة</h3><div className="grid gap-2 md:grid-cols-2">{(['companyName','companyType','sector','city','website','generalPhone','generalEmail','discoverySource','sourceUrl','notes'] as const).map(key=><input key={key} className={inputClass} value={editing[key] as string} onChange={(e)=>setEditing({...editing,[key]:e.target.value})} placeholder={key}/>) }<select className={inputClass} value={editing.reviewStatus} onChange={(e)=>setEditing({...editing,reviewStatus:e.target.value as DiscoveryStatus})}>{statuses.map(status=><option key={status}>{status}</option>)}</select></div><div className="mt-4 flex gap-2"><button className="rounded-xl bg-[#2f2417] px-4 py-2 text-white">حفظ</button><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border px-4 py-2">إلغاء</button></div></form></div>}
  </div>;
}
