'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { CRMPage } from './crm-shell';
import { isVerifiedDecisionMaker } from '../lib/domain/business';
import { businessAngle, generateMessage } from '../lib/intelligence/core';
import { companySegment } from '../lib/presentation';
import { buildBuyingCommittee, decisionAccessNextAction } from '../lib/intelligence/revenue-phase1';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';
import { nextReadinessAction, readinessScore, type ReadinessItem, type Gateway } from '../lib/readiness/core';
import { projectNextMove, type ProjectEntity, type ProjectPackage, type AccessPath, type ProjectFact } from '../lib/project-capture/core';

const safe=(value:unknown)=>String(value??'').trim();
const todayKey=()=>new Date().toISOString().slice(0,10);
const addDays=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);

type ActionKind='REPLY'|'FOLLOW_UP'|'OUTREACH'|'DECISION_ACCESS'|'RESEARCH'|'VENDOR'|'OPPORTUNITY'|'PROJECT_CAPTURE';
type Action={id:string;score:number;kind:ActionKind;company?:SimpleRow;contact?:SimpleRow;followUp?:SimpleRow;opportunity?:SimpleRow;project?:SimpleRow;title:string;why:string;next:string;href:string;due?:string;last?:string};

export function DailyWorkspace(){
 const [data,setData]=useState<Record<string,SimpleRow[]>>({});
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [expanded,setExpanded]=useState(false),[selected,setSelected]=useState<Action|null>(null),[messageBody,setMessageBody]=useState(''),[busy,setBusy]=useState(false);
 const today=todayKey();
 const load=async()=>{setLoading(true);setError('');try{
  const specs:[string,number,string][]=[['companies',500,'lead_score'],['contacts',500,'created_at'],['follow_ups',1000,'date'],['communication_events',1000,'occurred_at'],['opportunities',500,'updated_at'],['agent_jobs',1000,'created_at'],['messages',500,'created_at'],['meetings',500,'meeting_date'],['audit_events',500,'created_at'],['readiness_items',200,'item_key'],['qualification_gateways',100,'gateway_key'],['projects',500,'updated_at'],['project_entities',1500,'updated_at'],['project_packages',1500,'updated_at'],['project_access_paths',1500,'updated_at']];
  const rows=await Promise.all(specs.map(async([table,size,order])=>[table,(await simpleCrud.page(table,1,size,{order})).rows] as const));setData(Object.fromEntries(rows));
 }catch(reason){setError(reason instanceof Error?reason.message:'تعذر تجهيز قائمة اليوم.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);

 const companies=data.companies??[],contacts=data.contacts??[],followups=data.follow_ups??[],events=data.communication_events??[],opportunities=data.opportunities??[],jobs=data.agent_jobs??[],messages=data.messages??[],meetings=data.meetings??[],audit=data.audit_events??[],projects=data.projects??[],projectEntities=data.project_entities??[],projectPackages=data.project_packages??[],projectPaths=data.project_access_paths??[];
 const companyById=useMemo(()=>new Map(companies.map(c=>[String(c.id),c])),[companies]);
 const lastActivity=(companyId:unknown)=>safe([...events.filter(e=>e.company_id===companyId).map(e=>e.occurred_at),...audit.filter(e=>e.company_id===companyId).map(e=>e.created_at)].sort().at(-1));
 const hasFuturePause=(c:SimpleRow)=>Boolean(safe(c.nurture_until)&&safe(c.nurture_until)>today);
 const hasFutureFollowUp=(id:unknown)=>followups.some(f=>f.company_id===id&&safe(f.date||f.due_date)>today&&!['Completed','Cancelled'].includes(safe(f.status)));

 const actions=useMemo(()=>{
  const list:Action[]=[];
  events.filter(e=>e.direction==='INBOUND'&&!e.archived_at).forEach(e=>{const c=companyById.get(safe(e.company_id));if(!c||hasFuturePause(c))return;list.push({id:`reply-${e.id}`,score:100,kind:'REPLY',company:c,contact:contacts.find(x=>x.id===e.contact_id),title:safe(c.company_name),why:`رد وارد عبر ${safe(e.channel)||'قناة تواصل'}`,next:safe(e.next_action)||'مراجعة الرد وتحديد الخطوة التالية',href:`/outreach?tab=history&company_id=${c.id}`,last:safe(e.occurred_at)})});
  followups.filter(f=>safe(f.date||f.due_date)<=today&&!['Completed','Cancelled'].includes(safe(f.status))).forEach(f=>{const c=companyById.get(safe(f.company_id));if(!c||hasFuturePause(c))return;list.push({id:`follow-${f.id}`,score:95,kind:'FOLLOW_UP',company:c,contact:contacts.find(x=>x.id===f.contact_id),followUp:f,title:safe(c.company_name),why:safe(f.date||f.due_date)<today?'متابعة متأخرة':'متابعة مستحقة اليوم',next:safe(f.next_action||f.subject)||'تنفيذ المتابعة',href:`/companies/${c.id}`,due:safe(f.date||f.due_date),last:lastActivity(c.id)})});
  companies.filter(c=>!c.archived_at&&!hasFuturePause(c)).forEach(c=>{
    const person=contacts.find(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x));
    const outbound=events.some(e=>e.company_id===c.id&&e.direction==='OUTBOUND');
    const commercialReason=safe(c.latest_signal||c.why_now||c.vendor_registration_url)||(['SUBCONTRACT_BUYER'].includes(safe(c.relationship_type))?'مسار مقاولات باطن موثق في استراتيجية الحساب':'');
    if(person&&commercialReason&&!outbound&&!hasFutureFollowUp(c.id)) list.push({id:`outreach-${c.id}`,score:90+(c.priority==='A'?5:0),kind:'OUTREACH',company:c,contact:person,title:safe(c.company_name),why:`${commercialReason} · صانع قرار موثق ولم يُسجل تواصل فعلي بعد`,next:'تنفيذ أول تواصل بشري وتسجيله',href:`/companies/${c.id}`,last:lastActivity(c.id)});
    if(!person&&c.priority==='A'&&!hasFutureFollowUp(c.id)){const committee=buildBuyingCommittee(c,contacts.filter(x=>x.company_id===c.id));const next=decisionAccessNextAction(c,contacts.filter(x=>x.company_id===c.id));list.push({id:`access-${c.id}`,score:80,kind:'DECISION_ACCESS',company:c,title:safe(c.company_name),why:`أولوية A · Decision Access ${committee.accessScore}/100`,next:next.label,href:`/research?tab=verification&company_id=${c.id}`,last:lastActivity(c.id)})}
  });
  jobs.filter(j=>j.status==='manual_research_required').forEach(j=>{const c=companyById.get(safe(j.company_id));if(!c||c.priority==='A'||hasFuturePause(c)||hasFutureFollowUp(c.id))return;list.push({id:`research-${j.id}`,score:65,kind:'RESEARCH',company:c,title:safe(c.company_name),why:'نقص دليل يمنع التقدم التجاري',next:safe(j.research_target_department)||safe(j.research_target_role)||'استكمال البحث الموجّه',href:`/research?tab=manual&job_id=${j.id}`,last:safe(j.updated_at)})});
  opportunities.filter(o=>!['WON','LOST'].includes(safe(o.stage))&&safe(o.next_action_date)<=today).forEach(o=>{const c=companyById.get(safe(o.company_id));if(!c)return;list.push({id:`opp-${o.id}`,score:85,kind:'OPPORTUNITY',company:c,opportunity:o,title:safe(c.company_name),why:'إجراء فرصة مستحق',next:safe(o.next_action)||'تحديث الإجراء التالي',href:`/pipeline?opportunity_id=${o.id}`,due:safe(o.next_action_date),last:safe(o.updated_at)})});
  projects.filter(p=>!['WON','LOST','ON_HOLD'].includes(safe(p.stage))).forEach(p=>{
    const c=companyById.get(safe(p.owner_company_id));
    const pe=projectEntities.filter(x=>x.project_id===p.id),pp=projectPackages.filter(x=>x.project_id===p.id),pa=projectPaths.filter(x=>x.project_id===p.id);
    const move=projectNextMove(p as unknown as ProjectFact,pe as unknown as ProjectEntity[],pp as unknown as ProjectPackage[],pa as unknown as AccessPath[]);
    const verified=safe(p.verification_status)==='verified';
    const commercialStage=['VERIFIED','ACTIVE','RFQ','BID','NEGOTIATION'].includes(safe(p.stage));
    const score=verified&&commercialStage?93:verified?88:72;
    list.push({id:`project-${p.id}`,score,kind:'PROJECT_CAPTURE',company:c,project:p,title:safe(p.project_name)||'Project Candidate',why:verified?`${safe(p.why_now)||'مشروع موثق يحتاج Capture Plan'} · ${safe(p.route_to_revenue)||'Route غير محدد'}`:'Project Candidate يحتاج تحقق قبل المطاردة',next:move.label,href:`/projects/${p.id}`,last:safe(p.updated_at)});
  });
  const ordered=list.sort((a,b)=>b.score-a.score||safe(a.due).localeCompare(safe(b.due))||Number(b.company?.lead_score??0)-Number(a.company?.lead_score??0));
  const unique=new Map<string,Action>();ordered.forEach(item=>{const key=item.project?`project-${item.project.id}`:(safe(item.company?.id)||item.id);if(!unique.has(key))unique.set(key,item)});return [...unique.values()].slice(0,25);
 },[companies,contacts,events,followups,jobs,opportunities,audit,today,companyById,projects,projectEntities,projectPackages,projectPaths]);

 const meetingsThisWeek=useMemo(()=>{const now=new Date();const day=now.getDay();const diff=(day+6)%7;const monday=new Date(now);monday.setDate(now.getDate()-diff);monday.setHours(0,0,0,0);const next=new Date(monday);next.setDate(monday.getDate()+7);return meetings.filter(m=>{const d=new Date(safe(m.meeting_date||m.date||m.scheduled_at));return !Number.isNaN(d.getTime())&&d>=monday&&d<next&&!['Cancelled','CANCELLED'].includes(safe(m.status))}).length},[meetings]);
 const current=actions[0];
 const readinessItems=(data.readiness_items??[]) as unknown as ReadinessItem[];
 const readinessGateways=(data.qualification_gateways??[]) as unknown as Gateway[];
 const readinessNext=readinessItems.length&&readinessGateways.length?nextReadinessAction(readinessItems,readinessGateways):null;
 const readinessPct=readinessItems.length?readinessScore(readinessItems):null;
 const openAction=(item:Action)=>{setSelected(item);if(item.kind==='OUTREACH'&&item.company&&item.contact){const angle=businessAngle(item.company);setMessageBody(generateMessage({companyName:safe(item.company.company_name),recipientName:safe(item.contact.full_name||item.contact.name),segment:companySegment(item.company),angle:angle.angle,role:safe(item.contact.position)||angle.role,language:safe(item.company.recommended_language)==='ENGLISH'?'ENGLISH':'ARABIC',style:angle.style,type:angle.type,channel:'Email'}))}else setMessageBody('');};
 const snooze=async(item:Action)=>{if(!item.company)return;setBusy(true);try{if(item.followUp)await simpleCrud.update('follow_ups',item.followUp.id,{date:addDays(1),due_date:addDays(1),status:'Pending'});else await simpleCrud.create('follow_ups',{company_id:item.company.id,company_name:safe(item.company.company_name),contact_id:item.contact?.id??null,contact_person:safe(item.contact?.full_name||item.contact?.name),follow_up_type:'General',date:addDays(1),due_date:addDays(1),status:'Pending',priority:item.company.priority==='A'?'High':'Medium',subject:item.next,next_action:item.next});setSelected(null);setNotice('تم تأجيل الإجراء إلى الغد.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تأجيل الإجراء.')}finally{setBusy(false)}};
 const skipAccount=async(item:Action)=>{if(!item.company)return;setBusy(true);try{await simpleCrud.update('companies',item.company.id,{nurture_until:addDays(30),nurture_pause_reason:'USER_SKIPPED_FROM_DAILY'});await simpleCrud.create('audit_events',{company_id:item.company.id,entity_type:'companies',entity_id:item.company.id,action:'DAILY_SKIP_30_DAYS',details:{reason:item.why}});setSelected(null);setNotice('تم إبعاد الحساب من قائمة اليوم لمدة 30 يوماً.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحديث الحساب.')}finally{setBusy(false)}};
 const completeFollowUp=async(item:Action)=>{if(!item.followUp)return;setBusy(true);try{await simpleCrud.update('follow_ups',item.followUp.id,{status:'Completed'});setSelected(null);setNotice('تم إكمال المتابعة.');await load()}finally{setBusy(false)}};
 const logOutbound=async(item:Action)=>{if(!item.company||!item.contact||!messageBody.trim())return;setBusy(true);setError('');try{
  const draft=await simpleCrud.create('messages',{company_id:item.company.id,company_name:safe(item.company.company_name),contact_id:item.contact.id,recipient:safe(item.contact.full_name||item.contact.name),channel:'Email',subject:`تواصل مهني مع ${safe(item.company.company_name)}`,body:messageBody,status:'Contacted',draft_classification:'PERSONALIZED',language:safe(item.company.recommended_language)==='ENGLISH'?'ENGLISH':'ARABIC',sent_at:new Date().toISOString(),archive_reason:''});
  await simpleCrud.create('communication_events',{company_id:item.company.id,contact_id:item.contact.id,message_id:draft.id,subject:`تواصل مهني مع ${safe(item.company.company_name)}`,channel:'Email',direction:'OUTBOUND',recipient:safe(item.contact.email||item.contact.full_name||item.contact.name),occurred_at:new Date().toISOString(),status:'Sent',outcome:'تم التأكيد يدوياً أن التواصل نُفذ خارج النظام.',notes:'Human-approved execution from Daily Workspace. نوفافيرك did not send externally.',evidence_reference:'USER_CONFIRMED_OUTBOUND',next_action:'متابعة أولى إذا لم يصل رد',next_action_date:addDays(4)});
  await simpleCrud.create('follow_ups',{company_id:item.company.id,company_name:safe(item.company.company_name),contact_id:item.contact.id,contact_person:safe(item.contact.full_name||item.contact.name),follow_up_type:'Email',date:addDays(4),due_date:addDays(4),status:'Pending',priority:item.company.priority==='A'?'High':'Medium',subject:'متابعة أولى إذا لم يصل رد',next_action:'متابعة أولى إذا لم يصل رد'});
  setSelected(null);setNotice('تم تسجيل التواصل الفعلي وإنشاء متابعة بعد 4 أيام.');await load();
 }catch(reason){setError(reason instanceof Error?reason.message:'تعذر تسجيل التواصل.')}finally{setBusy(false)}};
 const copyMessage=async()=>{try{await navigator.clipboard.writeText(messageBody);setNotice('تم نسخ الرسالة. أرسلها من قناتك المعتادة ثم اضغط «سجلت التواصل».')}catch{setError('تعذر النسخ تلقائياً؛ انسخ النص يدوياً.')}};

 return <CRMPage title="اليوم" description="قرار واحد في كل مرة: من أتواصل معه، لماذا الآن، وما الخطوة التالية.">
  {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
  <section className="crm-card flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-xs font-bold text-[#7a5e1c]">المؤشر الوحيد لهذا الأسبوع</p><p className="mt-1 text-3xl font-black">{meetingsThisWeek}</p><p className="text-sm text-[#75664d]">اجتماعات محجوزة</p></div><div className="text-left"><p className="text-xs text-[#75664d]">هدف المرحلة</p><p className="font-bold">3 اجتماعات حقيقية</p></div></section>
  {loading?<div className="crm-empty animate-pulse">جارٍ اختيار أفضل تحرك تجاري الآن…</div>:current?<section className="crm-card overflow-hidden"><header className="border-b bg-[#faf5eb] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold text-[#7a5e1c]">NEXT BEST ACTION</p><h3 className="mt-1 text-xl font-bold">{current.title}</h3></div><span className="crm-chip status-warning">أولوية {safe(current.company?.priority)||'—'}</span></div></header><div className="grid gap-5 p-5 lg:grid-cols-[1fr_auto]"><div><p className="text-sm"><b>الشخص:</b> {safe(current.contact?.full_name||current.contact?.name)||'لم يتم توثيقه بعد'}</p><p className="mt-3 text-sm"><b>لماذا الآن:</b> {current.why}</p><p className="mt-2 text-sm"><b>الخطوة التالية:</b> {current.next}</p><p className="mt-3 text-xs text-[#75664d]">آخر نشاط: <span className="data-ltr">{current.last||'—'}</span>{current.due&&<> · الاستحقاق: <span className="data-ltr">{current.due}</span></>}</p></div><div className="flex flex-wrap content-start gap-2"><button onClick={()=>openAction(current)} className="btn-primary">نفّذ الآن</button><button onClick={()=>void snooze(current)} className="btn-ghost">أجّل للغد</button></div></div></section>:readinessNext?<section className="crm-card border-2 border-[#14554a] p-5"><p className="text-xs font-bold text-[#14554a]">NEXT READINESS ACTION</p><h3 className="mt-1 text-xl font-bold">{readinessNext.item.label}</h3><p className="mt-3 text-sm"><b>لماذا الآن:</b> لا يوجد إجراء تجاري أعلى أولوية؛ هذا العنصر يفتح {readinessNext.unlocks} بوابة ويقرّب {readinessNext.nears} بوابة.</p><p className="mt-2 text-sm"><b>جاهزية الشركة:</b> {readinessPct}%</p><div className="mt-4"><Link href="/readiness" className="btn-primary">فتح Market Readiness</Link></div><p className="mt-3 text-xs text-[#75664d]">استكمال الجاهزية لا يمنع بناء العلاقات أو البحث عن صناع القرار؛ هو شرط فقط للدخول الرسمي في المسارات التي تتطلب تأهيلاً.</p></section>:<div className="crm-empty">لا يوجد إجراء تجاري أو إجراء جاهزية مستحق الآن.</div>}
  {actions.length>1&&<section className="crm-card overflow-hidden"><button onClick={()=>setExpanded(v=>!v)} className="flex w-full items-center justify-between p-4 text-right"><div><h3 className="font-bold">الإجراءات التالية</h3><p className="text-xs text-[#75664d]">مطوية افتراضياً حتى يبقى التركيز على الإجراء الأول.</p></div><span className="crm-chip status-neutral">{actions.length-1} {expanded?'▲':'▼'}</span></button>{expanded&&<div className="divide-y">{actions.slice(1).map((item,index)=><article key={item.id} className="grid gap-3 p-4 md:grid-cols-[34px_1fr_auto] md:items-center"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f0e3ca] font-bold">{index+2}</span><div><strong>{item.title}</strong><p className="mt-1 text-xs text-[#75664d]">{item.why} · {item.next}</p></div><button onClick={()=>openAction(item)} className="btn-ghost">فتح</button></article>)}</div>}</section>}
  {selected&&<div className="fixed inset-0 z-[80] bg-black/45" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="absolute inset-y-0 left-0 w-full max-w-2xl overflow-y-auto bg-[#fffdf9] p-5 shadow-2xl"><div className="flex items-start justify-between gap-3 border-b pb-4"><div><p className="text-xs font-bold text-[#7a5e1c]">EXECUTION</p><h3 className="mt-1 text-xl font-bold">{selected.title}</h3><p className="mt-1 text-sm text-[#75664d]">{selected.why}</p></div><button onClick={()=>setSelected(null)} className="btn-ghost">إغلاق</button></div>
   <div className="mt-5 space-y-4"><div className="rounded-2xl border bg-white p-4"><p className="text-sm"><b>الشخص:</b> {safe(selected.contact?.full_name||selected.contact?.name)||'غير موثق'}</p><p className="mt-1 text-sm"><b>المنصب:</b> {safe(selected.contact?.position)||'—'}</p><p className="mt-1 text-sm"><b>الإجراء:</b> {selected.next}</p></div>
   {selected.kind==='OUTREACH'&&selected.contact?<><div><label className="mb-2 block text-sm font-bold">الرسالة</label><textarea value={messageBody} onChange={e=>setMessageBody(e.target.value)} className="min-h-[280px] w-full rounded-2xl border bg-white p-4 text-base leading-8"/></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void copyMessage()} className="btn-secondary">نسخ الرسالة</button><button disabled={busy} onClick={()=>void logOutbound(selected)} className="btn-primary">سجلت التواصل</button><button disabled={busy} onClick={()=>void snooze(selected)} className="btn-ghost">أجّل</button></div><p className="text-xs leading-6 text-[#75664d]">نوفافيرك لا يرسل البريد تلقائياً هنا. «سجلت التواصل» هو تأكيد بشري بأنك نفذت التواصل خارج النظام.</p></>:<div className="flex flex-wrap gap-2"><Link href={selected.href} className="btn-primary">فتح مسار التنفيذ</Link>{selected.followUp&&<button disabled={busy} onClick={()=>void completeFollowUp(selected)} className="btn-secondary">تم التنفيذ</button>}<button disabled={busy} onClick={()=>void snooze(selected)} className="btn-ghost">أجّل للغد</button></div>}
   {selected.company&&selected.kind!=='PROJECT_CAPTURE'&&<div className="border-t pt-4"><button disabled={busy} onClick={()=>void skipAccount(selected)} className="text-sm text-red-700 underline">غير مناسب الآن — إبعاده 30 يوماً</button></div>}</div>
  </aside></div>}
 </CRMPage>;
}
