'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { CRMPage } from './crm-shell';
import { isVerifiedDecisionMaker } from '../lib/domain/business';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';

const today=new Date().toISOString().slice(0,10),safe=(value:unknown)=>String(value??'').trim();
type Action={id:string;rank:number;company?:SimpleRow;contact?:SimpleRow;label:string;reason:string;action:string;href:string;due?:string;last?:string;followUp?:SimpleRow};

export function DailyWorkspace(){
  const [data,setData]=useState<Record<string,SimpleRow[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=async()=>{setLoading(true);try{const tables=['companies','contacts','follow_ups','communication_events','opportunities','agent_jobs','messages','audit_events'];const rows=await Promise.all(tables.map(async table=>{const size=table==='agent_jobs'?1000:500;const result=await simpleCrud.page(table,1,size,{order:'created_at'});return[table,result.rows] as const}));setData(Object.fromEntries(rows))}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تجهيز يومك.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const actions=useMemo(()=>{const companies=data.companies??[],contacts=data.contacts??[],followUps=data.follow_ups??[],events=data.communication_events??[],opportunities=data.opportunities??[],jobs=data.agent_jobs??[],audit=data.audit_events??[];const list:Action[]=[];const company=(id:unknown)=>companies.find(c=>c.id===id);const lastActivity=(id:unknown)=>safe([...events.filter(e=>e.company_id===id).map(e=>e.occurred_at),...audit.filter(e=>e.company_id===id).map(e=>e.created_at)].sort().at(-1));
    followUps.filter(f=>safe(f.date||f.due_date)<today&&!['Completed','Cancelled'].includes(safe(f.status))).forEach(f=>list.push({id:`f-${f.id}`,rank:1,company:company(f.company_id),label:safe(f.company_name||f.subject),reason:'متابعة متأخرة',action:safe(f.next_action||f.subject),href:`/follow-ups?company_id=${safe(f.company_id)}`,due:safe(f.date||f.due_date),last:lastActivity(f.company_id),followUp:f}));
    events.filter(e=>e.direction==='INBOUND'&&!e.archived_at).forEach(e=>list.push({id:`r-${e.id}`,rank:2,company:company(e.company_id),contact:contacts.find(c=>c.id===e.contact_id),label:safe(company(e.company_id)?.company_name),reason:`رد وارد: ${safe(e.outcome)||safe(e.channel)}`,action:safe(e.next_action)||'مراجعة الرد وتحديد الإجراء التالي',href:`/outreach?tab=history&company_id=${safe(e.company_id)}`,due:safe(e.next_action_date),last:safe(e.occurred_at)}));
    companies.filter(c=>contacts.some(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x))&&!events.some(e=>e.company_id===c.id&&e.direction==='OUTBOUND')).forEach(c=>{const dm=contacts.find(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x));list.push({id:`v-${c.id}`,rank:3,company:c,contact:dm,label:safe(c.company_name),reason:'صانع قرار موثق وجاهز للمراجعة',action:'مراجعة المسودة وتسجيل التواصل الحقيقي',href:`/outreach?tab=ready&company_id=${c.id}`,last:lastActivity(c.id)})});
    companies.filter(c=>c.priority==='A'&&!contacts.some(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x))).forEach(c=>list.push({id:`a-${c.id}`,rank:4,company:c,label:safe(c.company_name),reason:'Priority A بدون صانع قرار موثق',action:'إيجاد الشخص الصحيح وتوثيق المصدر',href:`/research?tab=manual&company_id=${c.id}`,last:lastActivity(c.id)}));
    companies.filter(c=>safe(c.vendor_registration_next_action)).forEach(c=>list.push({id:`vendor-${c.id}`,rank:5,company:c,label:safe(c.company_name),reason:'إجراء تسجيل مورد',action:safe(c.vendor_registration_next_action),href:`/vendor-registration?company_id=${c.id}`,last:lastActivity(c.id)}));
    jobs.filter(j=>j.status==='manual_research_required').forEach(j=>{const c=company(j.company_id);list.push({id:`job-${j.id}`,rank:6,company:c,label:safe(c?.company_name)||safe(j.agent_name),reason:'بحث يدوي مطلوب',action:safe(j.last_error)||'جمع دليل موثوق',href:`/research?tab=manual&job_id=${j.id}`,last:safe(j.updated_at)})});
    opportunities.filter(o=>!['WON','LOST'].includes(safe(o.stage))&&safe(o.next_action_date)<=today).forEach(o=>list.push({id:`opp-${o.id}`,rank:7,company:company(o.company_id),label:safe(o.title),reason:'إجراء فرصة مستحق',action:safe(o.next_action),href:`/pipeline?tab=opportunities&opportunity_id=${o.id}`,due:safe(o.next_action_date),last:safe(o.updated_at)}));
    companies.filter(c=>c.priority==='B'&&!contacts.some(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x))).forEach(c=>list.push({id:`b-${c.id}`,rank:8,company:c,label:safe(c.company_name),reason:'Priority B تحتاج صانع قرار',action:'استكمال جهة الاتصال',href:`/research?tab=manual&company_id=${c.id}`,last:lastActivity(c.id)}));
    companies.filter(c=>c.priority==='C'&&!contacts.some(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x))).forEach(c=>list.push({id:`c-${c.id}`,rank:9,company:c,label:safe(c.company_name),reason:'Priority C تحتاج بيانات',action:'مراجعة عند توفر السعة',href:`/research?tab=manual&company_id=${c.id}`,last:lastActivity(c.id)}));
    return list.sort((a,b)=>a.rank-b.rank||safe(a.due).localeCompare(safe(b.due))||Number(b.company?.lead_score??0)-Number(a.company?.lead_score??0)).slice(0,20)},[data]);
  const complete=async(action:Action)=>{if(!action.followUp)return;await simpleCrud.update('follow_ups',action.followUp.id,{status:'Completed'});setNotice('تم إكمال المتابعة.');await load()};
  const snooze=async(action:Action)=>{const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);if(action.followUp)await simpleCrud.update('follow_ups',action.followUp.id,{date:tomorrow,due_date:tomorrow,status:'Pending'});else if(action.company)await simpleCrud.create('follow_ups',{company_id:action.company.id,company_name:safe(action.company.company_name),follow_up_type:'General',date:tomorrow,due_date:tomorrow,status:'Pending',priority:safe(action.company.priority)==='A'?'High':'Medium',subject:action.action,next_action:action.action});setNotice(`تم حفظ التأجيل إلى ${tomorrow} في Supabase.`);await load()};
  return <CRMPage title="اليوم" description="أهم الإجراءات التالية فقط، مرتبة حسب الاستحقاق والدليل والأولوية.">{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{notice}</p>}{loading?<div className="crm-empty animate-pulse">جارٍ ترتيب إجراءات اليوم...</div>:<section className="crm-card overflow-hidden"><div className="border-b bg-[#faf5eb] p-4"><h3 className="font-bold">Next Best Actions</h3><p className="text-xs text-[#75664d]">{actions.length} إجراءً مرتبة — لا تُحتسب المسودة كتواصل.</p></div><div className="divide-y">{actions.map((item,index)=><article key={item.id} className="grid gap-3 p-4 md:grid-cols-[40px_1fr_auto] md:items-center"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0e3ca] font-bold">{index+1}</span><div><div className="flex flex-wrap items-center gap-2"><Link href={item.company?`/companies/${item.company.id}`:item.href} className="font-bold hover:text-[#9a742b]">{item.label}</Link>{item.company&&<span className="crm-chip bg-amber-50">Priority {safe(item.company.priority)||'C'}</span>}</div><p className="mt-1 text-sm"><b>السبب:</b> {item.reason}</p><p className="text-sm"><b>المطلوب:</b> {item.action}</p><p className="mt-1 text-xs text-[#75664d]">الشخص: {safe(item.contact?.full_name||item.contact?.name)||'غير موثق'} · الدليل: {item.contact&&isVerifiedDecisionMaker(item.contact)?'VERIFIED':'NEEDS EVIDENCE'} · الاستحقاق: {item.due||'اليوم'} · آخر نشاط: {item.last||'—'}</p></div><div className="flex flex-wrap gap-2 text-xs"><Link href={item.href} className="rounded-lg bg-[#2f2417] px-3 py-2 text-white">فتح الإجراء</Link>{item.followUp&&<button onClick={()=>void complete(item)} className="rounded-lg bg-emerald-700 px-3 py-2 text-white">إكمال</button>}<button onClick={()=>void snooze(item)} className="rounded-lg border px-3 py-2">تأجيل</button></div></article>)}{!actions.length&&<div className="crm-empty m-4">لا توجد إجراءات مستحقة.</div>}</div></section>}</CRMPage>;
}
