'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { CRMPage } from './crm-shell';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';
import { exclusionReason, nurtureDecision } from '../lib/intelligence/smart-nurture';
const text=(value:unknown)=>String(value??'').trim();
export function EmailCenterWorkspace(){
 const [data,setData]=useState<Record<string,SimpleRow[]>>({companies:[],contacts:[],messages:[],communication_events:[],opportunities:[],outreach_campaigns:[],sales_kit_assets:[]}),[tab,setTab]=useState('New'),[notice,setNotice]=useState('');
 const load=async()=>{const names=['companies','contacts','messages','communication_events','opportunities','outreach_campaigns','sales_kit_assets'];const pairs=await Promise.all(names.map(async name=>[name,await simpleCrud.list(name)] as const));setData(Object.fromEntries(pairs));};
 useEffect(()=>{void load().catch(error=>setNotice(error instanceof Error?error.message:'تعذر التحميل.'));},[]);
 const companies=data.companies,contacts=data.contacts,messages=data.messages,events=data.communication_events,opportunities=data.opportunities,kits=data.sales_kit_assets;
 const suggestions=useMemo(()=>companies.map(company=>({company,decision:nurtureDecision(company,{events:events.filter(row=>row.company_id===company.id),opportunities:opportunities.filter(row=>row.company_id===company.id)}),excluded:exclusionReason(company,{contacts:contacts.filter(row=>row.company_id===company.id),events:events.filter(row=>row.company_id===company.id),opportunities:opportunities.filter(row=>row.company_id===company.id)})})).filter(item=>!item.excluded&&['CONTACT_NOW','FOLLOW_UP','NURTURE','RE_ENGAGE'].includes(item.decision.decision)),[companies,contacts,events,opportunities]);
 const rows:SimpleRow[]=tab==='Campaigns'?data.outreach_campaigns??[]:tab==='Attachments'?kits:tab==='History'?events:messages.filter(row=>tab==='Drafts'?text(row.status)==='Draft':tab==='Approved'?text(row.status)==='Approved':tab==='Ready'?['Approved','Ready for Manual Send'].includes(text(row.status)):true);
 async function saveSuggestion(item:typeof suggestions[number]){try{const attachment=kits.find(asset=>text(asset.asset_type)==='Company Profile')??kits[0];await simpleCrud.create('nurture_suggestions',{company_id:item.company.id,decision:item.decision.decision,reason:item.decision.reason,recommended_channel:'EMAIL',recommended_message_type:item.decision.decision==='FOLLOW_UP'?'FOLLOW-UP':'NURTURE',recommended_attachment_id:attachment?.id??null,suggested_send_date:item.decision.timing===0?new Date().toISOString().slice(0,10):null,status:'PENDING'});setNotice('تم حفظ الاقتراح في Supabase؛ لا يتم إرسال أي بريد.');}catch(error){setNotice(error instanceof Error?error.message:'تعذر حفظ الاقتراح.');}}
 const tabs=['New','Campaigns','Nurture','Drafts','Approved','Ready','History','Templates','Attachments'];
 return <CRMPage title="مركز البريد والتواصل" description="مسودات وحملات وتغذية دورية مرتبطة بالشركات نفسها. EXTERNAL SENDING: DISABLED."><div className="crm-card flex flex-wrap gap-2 p-3">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?'btn-primary':'btn-ghost'}>{item}</button>)}<Link href="/campaigns" className="btn-secondary">إنشاء حملة مخصصة</Link></div><div className="mt-3 grid gap-3 md:grid-cols-4"><div className="crm-card p-3"><b>{suggestions.length}</b><p className="text-xs">Nurture suggestions</p></div><div className="crm-card p-3"><b>{messages.filter(row=>text(row.status)==='Draft').length}</b><p className="text-xs">Drafts</p></div><div className="crm-card p-3"><b>{messages.filter(row=>text(row.status)==='Approved').length}</b><p className="text-xs">Approved</p></div><div className="crm-card p-3"><b>{companies.filter(row=>text(row.nurture_status).toUpperCase()==='PAUSED'||row.do_not_contact===true).length}</b><p className="text-xs">Paused</p></div></div>{notice&&<p className="mt-3 text-sm text-emerald-700">{notice}</p>}<section className="crm-card mt-3 p-4">{tab==='Nurture'?<div className="space-y-3">{suggestions.map(item=><article key={item.company.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><Link href={`/companies/${item.company.id}`} className="font-bold">{text(item.company.company_name)}</Link><span className="crm-chip status-warning">{item.decision.decision}</span></div><p className="mt-2 text-sm">{item.decision.reason}</p><p className="mt-1 text-xs">Timing: {item.decision.timing===0?'اليوم':item.decision.timing??'عند وجود سبب جديد'} — لا يُنشأ بريد بلا سبب حقيقي.</p><button onClick={()=>void saveSuggestion(item)} className="btn-primary mt-2">حفظ الاقتراح للمراجعة</button></article>)}{!suggestions.length&&<div className="crm-empty">لا توجد اقتراحات مستحقة.</div>}</div>:<div className="space-y-2">{rows.map(row=><article key={row.id} className="rounded-xl border p-3"><b>{text(row.company_name||row.name||row.subject||row.direction||'سجل محفوظ')}</b><p className="mt-1 text-sm">{text(row.subject||row.reason||row.outreach_type||row.status)}</p></article>)}{!rows.length&&<div className="crm-empty">لا توجد بيانات محفوظة لهذه الفئة.</div>}</div>}</section><p className="mt-3 text-xs">الإرسال الخارجي معطل بالكامل. اعتماد المسودة لا ينفذ إرسالاً.</p></CRMPage>;
}
