'use client';
import { useMemo, useRef, useState } from 'react';
import type { SimpleRow } from '../lib/supabase/simple-crud';

const s = (value: unknown) => String(value ?? '').trim();
export function GmailComposeModal({ companies, contacts, onClose, onSave }: { companies:SimpleRow[]; contacts:SimpleRow[]; onClose:()=>void; onSave:(values:Record<string,unknown>)=>Promise<void> }) {
  const editor=useRef<HTMLDivElement>(null),[companyId,setCompanyId]=useState(''),[recipient,setRecipient]=useState(''),[subject,setSubject]=useState(''),[busy,setBusy]=useState(false);
  const company=companies.find(row=>row.id===companyId),companyContacts=useMemo(()=>contacts.filter(row=>row.company_id===companyId),[companyId,contacts]);
  const command=(name:string,value?:string)=>{editor.current?.focus();document.execCommand(name,false,value)};
  const chooseCompany=(id:string)=>{setCompanyId(id);const selected=companies.find(row=>row.id===id),contact=contacts.find(row=>row.company_id===id&&s(row.email));setRecipient(s(contact?.email||selected?.general_email||selected?.email));setSubject(selected?`فرص تعاون مع ${s(selected.company_name)}`:'')};
  const save=async()=>{const body=editor.current?.innerText.trim()||'';if(!companyId||!subject.trim()||!body)return;setBusy(true);await onSave({company_id:companyId,company_name:s(company?.company_name),contact_id:companyContacts.find(row=>s(row.email)===recipient)?.id||null,recipient,channel:'Email',subject,body,status:'Draft',draft_classification:'PREPARATION',language:'ARABIC'});setBusy(false)};
  const addLink=()=>{const url=window.prompt('أدخل رابطًا يبدأ بـ https://');if(url)command('createLink',url)};
  return <div className="fixed inset-0 z-[110] flex items-end justify-center bg-black/60 p-3 md:items-center"><section className="flex max-h-[94vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-[#454b5c] bg-[#20232b] shadow-2xl">
    <header className="flex items-center justify-between bg-[#30343e] px-4 py-3"><h2 className="font-bold">رسالة جديدة</h2><button type="button" onClick={onClose} className="btn-ghost" aria-label="إغلاق">✕</button></header>
    <div className="border-b border-[#454b5c] p-3"><select value={companyId} onChange={event=>chooseCompany(event.target.value)} className="w-full rounded-xl border p-2"><option value="">اختر الشركة</option>{companies.map(row=><option key={row.id} value={row.id}>{s(row.company_name)}</option>)}</select></div>
    <label className="flex items-center gap-3 border-b border-[#454b5c] px-4 py-3 text-sm"><span className="text-[#aab0bf]">إلى</span><input value={recipient} onChange={event=>setRecipient(event.target.value)} dir="ltr" placeholder="email@company.com" className="min-w-0 flex-1 bg-transparent outline-none"/></label>
    <label className="flex items-center gap-3 border-b border-[#454b5c] px-4 py-3 text-sm"><span className="text-[#aab0bf]">الموضوع</span><input value={subject} onChange={event=>setSubject(event.target.value)} className="min-w-0 flex-1 bg-transparent outline-none"/></label>
    <div className="flex flex-wrap gap-1 border-b border-[#454b5c] px-3 py-2" role="toolbar" aria-label="تنسيق الرسالة"><button type="button" onClick={()=>command('bold')} className="btn-ghost font-black">B</button><button type="button" onClick={()=>command('italic')} className="btn-ghost italic">I</button><button type="button" onClick={()=>command('underline')} className="btn-ghost underline">U</button><button type="button" onClick={()=>command('strikeThrough')} className="btn-ghost line-through">S</button><button type="button" onClick={()=>command('insertUnorderedList')} className="btn-ghost">• قائمة</button><button type="button" onClick={()=>command('insertOrderedList')} className="btn-ghost">1. قائمة</button><button type="button" onClick={()=>command('justifyRight')} className="btn-ghost">⇥</button><button type="button" onClick={()=>command('justifyCenter')} className="btn-ghost">≡</button><button type="button" onClick={addLink} className="btn-ghost">🔗</button><button type="button" onClick={()=>command('removeFormat')} className="btn-ghost">Tx</button></div>
    <div ref={editor} contentEditable suppressContentEditableWarning dir="rtl" data-placeholder="اكتب رسالتك هنا…" className="min-h-[360px] flex-1 overflow-auto p-5 text-base leading-8 outline-none empty:before:text-[#777f91] empty:before:content-[attr(data-placeholder)]"/>
    <footer className="flex flex-wrap items-center gap-2 border-t border-[#454b5c] p-3"><button disabled={busy||!companyId||!subject.trim()} onClick={()=>void save()} className="btn-primary">{busy?'جارٍ الحفظ…':'حفظ المسودة'}</button><button type="button" onClick={()=>editor.current&&(editor.current.innerHTML='')} className="btn-ghost">🗑 مسح</button><span className="me-auto text-xs text-[#8f96a3]">لن تُرسل الرسالة عند حفظها.</span></footer>
  </section></div>;
}
