'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { isVerifiedDecisionMaker } from '../lib/domain/business';
import { businessAngle, MESSAGE_STYLES, MESSAGE_TYPES, type MessageStyle, type MessageType, type TargetSegment } from '../lib/intelligence/core';
import { conversationStrategy, evaluateMessageQuality, generateProfessionalMessage, type ConversationObjective, type ConversationStrategy } from '../lib/intelligence/v6';
import { CORE_SEGMENTS, SEGMENT_LABELS, companySegment } from '../lib/presentation';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';

const safe = (value: unknown) => String(value ?? '').trim();
const styleLabels: Record<MessageStyle, string> = { DIRECT:'مباشرة', RELATIONSHIP:'بناء علاقة', OPPORTUNITY_LED:'مرتبطة بفرصة' };
type UiChannel = 'Email' | 'LinkedIn' | 'WhatsApp' | 'Call';
type SegmentFilter='ALL'|TargetSegment;
type Readiness='ALL'|'VERIFIED'|'DIRECT_EMAIL'|'MISSING_PERSON';

function objectiveFor(value: MessageType): ConversationObjective {
  if (value === 'VENDOR_REGISTRATION') return 'VENDOR_REGISTRATION';
  if (value === 'SUBCONTRACTING') return 'SUBCONTRACTING';
  if (value === 'MEETING_REQUEST') return 'MEETING_REQUEST';
  if (value === 'RFQ_FOLLOW_UP') return 'RFQ_RESPONSE_PREP';
  if (value.startsWith('FOLLOW_UP') || value === 'FINAL_FOLLOW_UP') return 'FOLLOW_UP';
  if (value === 'PROJECT_OPPORTUNITY') return 'PROJECT_DISCUSSION';
  if (value === 'INDUSTRIAL_SERVICES') return 'INDUSTRIAL_SUPPORT';
  return 'INTRODUCTION';
}
function providerChannel(value: UiChannel): ConversationStrategy['channel'] { return value === 'Email' ? 'EMAIL' : value === 'LinkedIn' ? 'LINKEDIN' : value === 'WhatsApp' ? 'WHATSAPP' : 'CALL_SCRIPT'; }

export function OutreachStrategyWorkspace({ companies, contacts, messages, onSaved }: { companies:SimpleRow[]; contacts:SimpleRow[]; messages:SimpleRow[]; onSaved:()=>Promise<void> }) {
  const params=useSearchParams();
  const [query, setQuery] = useState('');
  const [segment, setSegment] = useState<SegmentFilter>('ALL');
  const [priority, setPriority] = useState('ALL');
  const [readiness, setReadiness] = useState<Readiness>('ALL');
  const [page, setPage] = useState(1);
  const [checked, setChecked] = useState<string[]>([]);
  const [selected, setSelected] = useState<SimpleRow | null>(null);
  const [language, setLanguage] = useState<'ARABIC' | 'ENGLISH'>('ARABIC');
  const [style, setStyle] = useState<MessageStyle>('DIRECT');
  const [kind, setKind] = useState<MessageType>('INITIAL_INTRODUCTION');
  const [channel, setChannel] = useState<UiChannel>('Email');
  const [body, setBody] = useState('');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [bulkBusy,setBulkBusy]=useState(false);
  const [sendScope,setSendScope]=useState<'FILTERED'|'SELECTED'>('FILTERED');
  useEffect(()=>{const requested=params.get('segment'); if(requested && (requested==='ALL'||CORE_SEGMENTS.includes(requested as TargetSegment))) setSegment(requested as SegmentFilter)},[params]);

  const verifiedContact = (company: SimpleRow) => contacts.find(contact => contact.company_id === company.id && isVerifiedDecisionMaker(contact));
  const directEmail = (company:SimpleRow) => safe(verifiedContact(company)?.email);
  const segmentOf=(company:SimpleRow)=>companySegment(company);
  const rows = useMemo(() => companies.filter(company => !company.archived_at).filter(company => segment==='ALL' || segmentOf(company)===segment).filter(company => priority==='ALL' || safe(company.priority)===priority).filter(company => { const contact=verifiedContact(company); if(readiness==='VERIFIED') return Boolean(contact); if(readiness==='DIRECT_EMAIL') return Boolean(contact&&safe(contact.email)); if(readiness==='MISSING_PERSON') return !contact; return true; }).filter(company => !query || `${safe(company.company_name)} ${safe(company.sector)} ${SEGMENT_LABELS[segmentOf(company)]}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => safe(a.priority).localeCompare(safe(b.priority)) || Number(b.lead_score ?? 0) - Number(a.lead_score ?? 0)), [companies, contacts, priority, query, readiness, segment]);
  const visible = rows.slice((page - 1) * 20, page * 20);
  const pages = Math.max(1, Math.ceil(rows.length / 20));
  const checkedRows=rows.filter(row=>checked.includes(String(row.id)));
  const eligibleChecked=checkedRows.filter(company=>Boolean(verifiedContact(company)&&directEmail(company)));
  const eligibleFiltered=rows.filter(company=>Boolean(verifiedContact(company)&&directEmail(company)));
  const hasCommercialReason=(company:SimpleRow)=>Boolean(safe(company.latest_signal)||safe(company.why_now)||safe(company.vendor_registration_url)||['MAIN_CONTRACTOR','INDUSTRIAL_CONTRACTOR'].includes(segmentOf(company)));
  const bulkTargets=(sendScope==='FILTERED'?eligibleFiltered:eligibleChecked).filter(hasCommercialReason);
  const stats=useMemo(()=>({total:rows.length,verified:rows.filter(company=>Boolean(verifiedContact(company))).length,emailReady:rows.filter(company=>Boolean(directEmail(company))).length,missing:rows.filter(company=>!verifiedContact(company)).length}),[rows,contacts]);

  const strategyFor = (company: SimpleRow, nextLanguage = language, nextStyle = style, nextKind = kind, nextChannel = channel) => { const base = conversationStrategy({ company, contacts, events:[], language:nextLanguage, channel:providerChannel(nextChannel), objective:objectiveFor(nextKind) }); return { ...base, messageStyle:nextStyle, messageType:nextKind }; };
  const generatedFor = (company: SimpleRow, nextLanguage = language, nextStyle = style, nextKind = kind, nextChannel = channel) => { const contact = verifiedContact(company); return generateProfessionalMessage({ strategy:strategyFor(company, nextLanguage, nextStyle, nextKind, nextChannel), companyName:safe(company.company_name), recipientName:safe(contact?.full_name || contact?.name), verifiedRecipient:Boolean(contact), evidence:contact ? [{ label:'Decision maker', value:safe(contact.full_name || contact.name), source:safe(contact.source_url || contact.source) }] : [] }); };
  const open = (company: SimpleRow) => { const intelligence = businessAngle(company); const nextLanguage = safe(company.recommended_language) === 'ENGLISH' ? 'ENGLISH' : 'ARABIC'; setSelected(company); setLanguage(nextLanguage); setStyle(intelligence.style); setKind(intelligence.type); setChannel('Email'); setBody(generatedFor(company, nextLanguage, intelligence.style, intelligence.type, 'Email').body); setError(''); };
  const selectedStrategy = selected ? strategyFor(selected) : null;
  const personalization = selected ? generatedFor(selected).personalizationLevel : 0;
  const quality = selected && selectedStrategy ? evaluateMessageQuality({ body, companyName:safe(selected.company_name), businessAngle:selectedStrategy.businessAngle, channel:selectedStrategy.channel, personalizationLevel:personalization, relationshipAware:selectedStrategy.relationshipStage !== 'TARGET', evidenceSafe:!body.match(/مشروع حالي|مشروع قائم|current project|awarded project/i), existingDrafts:messages.map(message => safe(message.body)) }) : null;

  const persistDraft=async(company:SimpleRow,nextBody:string,nextLanguage:'ARABIC'|'ENGLISH',nextStyle:MessageStyle,nextKind:MessageType,nextChannel:UiChannel)=>{
    const contact=verifiedContact(company); const strategy=strategyFor(company,nextLanguage,nextStyle,nextKind,nextChannel); const generated=generatedFor(company,nextLanguage,nextStyle,nextKind,nextChannel);
    const draftQuality=evaluateMessageQuality({body:nextBody,companyName:safe(company.company_name),businessAngle:strategy.businessAngle,channel:strategy.channel,personalizationLevel:generated.personalizationLevel,relationshipAware:strategy.relationshipStage!=='TARGET',evidenceSafe:true,existingDrafts:messages.map(message=>safe(message.body))});
    const strategyRow = await simpleCrud.create('conversation_strategies', {company_id:company.id, contact_id:contact?.id ?? null, objective:strategy.objective,target_segment:strategy.targetSegment, target_role:strategy.targetRole, relationship_stage:strategy.relationshipStage,business_angle:strategy.businessAngle, message_type:nextKind, message_style:nextStyle, language:nextLanguage, channel:strategy.channel,cta:strategy.cta, risk:strategy.risk, context_summary:strategy.contextSummary, status:'DRAFT'});
    await simpleCrud.create('messages', {company_id:company.id, company_name:safe(company.company_name), contact_id:contact?.id ?? null, strategy_id:strategyRow.id,recipient:safe(contact?.full_name || contact?.name), channel:nextChannel,subject:nextLanguage === 'ARABIC' ? `تواصل مهني مع ${safe(company.company_name)}` : `Business introduction — ${safe(company.company_name)}`,body:nextBody, status:'Draft', draft_classification:contact ? 'PERSONALIZED' : 'PREPARATION', language:nextLanguage, message_type:nextKind, message_style:nextStyle,quality_score:draftQuality.score, quality_status:draftQuality.status, quality_issues:draftQuality.warnings, quality_breakdown:draftQuality.dimensions,duplicate_similarity:draftQuality.duplicateSimilarity, duplicate_warning:draftQuality.warnings.find(item => item.includes('GENERIC_PATTERN')) || '',personalization_level:generated.personalizationLevel, relationship_context_summary:strategy.contextSummary});
  };
  const save = async () => { if (!selected || !quality || !selectedStrategy) return; if (messages.length && !Object.hasOwn(messages[0], 'quality_score')) { setError('تخزين V6 غير مفعّل بعد؛ يجب تطبيق migration الإضافية الآمنة أولاً.'); return; } try { await persistDraft(selected,body,language,style,kind,channel); setSelected(null); setNotice('تم حفظ المسودة المخصصة للمراجعة.'); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر حفظ الاستراتيجية والمسودة.'); } };
  const bulkPrepare=async()=>{ if(sendScope==='SELECTED'&&!checkedRows.length){setError('اختر شركة واحدة على الأقل أو اختر وضع كل نتائج الفلتر.');return} if(!bulkTargets.length){setError('لا توجد شركات مؤهلة: يلزم صانع قرار موثق + بريد مباشر + Trigger أو استراتيجية تجارية واضحة.');return} if(messages.length && !Object.hasOwn(messages[0], 'quality_score')){setError('تخزين V6 غير مفعّل بعد؛ لا يمكن إنشاء قائمة الإرسال بأمان.');return} setBulkBusy(true);setError('');setNotice(''); try{ let created=0; for(const company of bulkTargets){ const intelligence=businessAngle(company); const nextLanguage=safe(company.recommended_language)==='ENGLISH'?'ENGLISH':'ARABIC'; const generated=generatedFor(company,nextLanguage,intelligence.style,intelligence.type,'Email'); await persistDraft(company,generated.body,nextLanguage,intelligence.style,intelligence.type,'Email'); created+=1; } setNotice(`تم تجهيز ${created} مسودة مخصصة لقائمة الإرسال (${sendScope==='FILTERED'?'كل نتائج الفلتر':'الشركات المحددة'}). لم يتم إرسال أي بريد تلقائياً.`); if(sendScope==='SELECTED')setChecked([]); await onSaved(); }catch(reason){setError(reason instanceof Error?reason.message:'تعذر تجهيز قائمة الإرسال.')}finally{setBulkBusy(false)} };
  const selectAllFiltered=()=>setChecked(rows.map(row=>String(row.id))); const clearSelection=()=>setChecked([]);
  const playbook=segment==='REAL_ESTATE_DEVELOPER'?{goal:'الدخول لقائمة المقاولين + الوصول إلى Projects/Contracts',why:'المطور يحتاج مقاولاً مؤهلاً قبل ظهور الحزمة.',cta:'طلب مسار التأهيل واجتماع تعريفي قصير'}:segment==='ENGINEERING_CONSULTANT'?{goal:'بناء علاقة إحالة وإدراج ضمن المقاولين المحتملين',why:'الاستشاري مؤثر في الترشيح والمناقصات.',cta:'تعريف القدرات وطلب مسؤول المشاريع/المناقصات'}:segment==='MAIN_CONTRACTOR'||segment==='INDUSTRIAL_CONTRACTOR'?{goal:'الوصول إلى Subcontracts/Procurement والحزم الحالية',why:'توقيت الحزمة أهم من التعريف العام.',cta:'طلب الحزم المفتوحة وآلية تأهيل المقاولين الفرعيين'}:segment==='INDUSTRIAL_FACTORY'||segment==='MANUFACTURER'?{goal:'الوصول إلى Projects/Engineering ثم Procurement',why:'الفرص تبدأ من توسعة/صيانة/تعديل قبل الشراء.',cta:'تحديد مسؤول المشاريع ومسار Vendor Registration'}:{goal:'تحديد بوابة الدخول التجارية والشخص الصحيح',why:'لا يوجد مسار واحد يناسب هذا القطاع.',cta:'طلب توجيه للقسم المسؤول والتأهيل'};

  return <section className="space-y-4">
    <section className="crm-card border-r-4 border-r-[#b78d38] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#9a742b]">COMMERCIAL PURSUIT</p><h3 className="text-xl font-bold">خطة الدخول للحسابات الحالية</h3><p className="mt-1 text-sm text-[#75664d]">كل قائمة مرتبطة بقطاع، شخص مستهدف، وهدف تجاري؛ وليست حملة بريد عامة.</p></div><span className="crm-chip status-warning">{segment==='ALL'?'اختر قطاعاً لزيادة دقة الخطة':SEGMENT_LABELS[segment]}</span></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#f8f1e4] p-3"><p className="text-xs text-[#75664d]">الهدف التجاري</p><b className="mt-1 block">{playbook.goal}</b></div><div className="rounded-xl bg-[#f8f1e4] p-3"><p className="text-xs text-[#75664d]">لماذا هذا المسار؟</p><b className="mt-1 block">{playbook.why}</b></div><div className="rounded-xl bg-[#f8f1e4] p-3"><p className="text-xs text-[#75664d]">الـ CTA المقترح</p><b className="mt-1 block">{playbook.cta}</b></div></div></section>
    <section className="crm-card p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#9a742b]">OUTREACH CONTROL</p><h3 className="text-xl font-bold">قائمة الإرسال والاستهداف</h3><p className="mt-1 max-w-3xl text-sm text-[#75664d]">اختر القطاع ثم قرر: كل الشركات المطابقة أو شركات محددة فقط. البريد العام لا يعتبر وصولاً لصانع القرار.</p></div><div className="flex flex-wrap gap-2"><button onClick={selectAllFiltered} className="btn-secondary">تحديد كل النتائج ({rows.length})</button><button onClick={clearSelection} className="btn-ghost">إلغاء التحديد</button></div></div>
      <div className="mt-4 grid gap-2 lg:grid-cols-[1.2fr_1fr_.7fr_1fr]"><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="ابحث بالشركة أو القطاع" className="rounded-xl border p-2.5"/><select value={segment} onChange={event=>{setSegment(event.target.value as SegmentFilter);setPage(1);setChecked([])}} className="rounded-xl border p-2.5"><option value="ALL">كل القطاعات</option>{CORE_SEGMENTS.map(id=><option key={id} value={id}>{SEGMENT_LABELS[id]}</option>)}</select><select value={priority} onChange={event=>{setPriority(event.target.value);setPage(1)}} className="rounded-xl border p-2.5"><option value="ALL">كل الأولويات</option><option value="A">A</option><option value="B">B</option><option value="C">C</option></select><select value={readiness} onChange={event=>{setReadiness(event.target.value as Readiness);setPage(1)}} className="rounded-xl border p-2.5"><option value="ALL">كل حالات الوصول</option><option value="VERIFIED">صانع قرار موثق</option><option value="DIRECT_EMAIL">جاهز للبريد المباشر</option><option value="MISSING_PERSON">ينقصه الشخص الصحيح</option></select></div>
      <div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4"><div className="rounded-xl bg-[#f8f1e4] p-3 text-center"><b className="text-2xl">{stats.total}</b><p className="text-xs">نتائج الاستهداف</p></div><div className="rounded-xl bg-[#f8f1e4] p-3 text-center"><b className="text-2xl">{stats.verified}</b><p className="text-xs">صانع قرار موثق</p></div><div className="rounded-xl bg-emerald-50 p-3 text-center"><b className="text-2xl text-emerald-800">{stats.emailReady}</b><p className="text-xs text-emerald-800">جاهز لبريد مباشر</p></div><div className="rounded-xl bg-amber-50 p-3 text-center"><b className="text-2xl text-amber-800">{stats.missing}</b><p className="text-xs text-amber-800">ينقصه الشخص الصحيح</p></div></div>
      <div className="mt-4 rounded-xl border border-[#ead9b3] bg-white p-3"><div className="flex flex-wrap items-center gap-3"><b>نطاق قائمة الإرسال:</b><label className="flex items-center gap-2 text-sm"><input type="radio" checked={sendScope==='FILTERED'} onChange={()=>setSendScope('FILTERED')}/>كل نتائج الفلتر الحالية <span className="crm-chip status-neutral">{eligibleFiltered.length} جاهزة</span></label><label className="flex items-center gap-2 text-sm"><input type="radio" checked={sendScope==='SELECTED'} onChange={()=>setSendScope('SELECTED')}/>شركات أحددها بنفسي <span className="crm-chip status-neutral">{eligibleChecked.length}/{checked.length}</span></label><button disabled={bulkBusy||!bulkTargets.length} onClick={()=>void bulkPrepare()} className="btn-primary mr-auto disabled:opacity-40">{bulkBusy?'جارٍ التجهيز…':`تجهيز قائمة الإرسال (${bulkTargets.length})`}</button></div><p className="mt-2 text-xs text-[#75664d]">الجاهزية = صانع قرار موثق + بريد مباشر. الإرسال الخارجي ما زال تحت قرار المستخدم.</p></div>
      {notice&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    </section>
    <div className="grid gap-3 md:grid-cols-2">{visible.map(company => { const intelligence=businessAngle(company), contact=verifiedContact(company),isChecked=checked.includes(String(company.id)); return <article key={company.id} className={`crm-card p-4 ${isChecked?'ring-2 ring-[#b78d38]':''}`}><div className="flex items-start gap-3"><input aria-label="تحديد الشركة" type="checkbox" checked={isChecked} onChange={event=>setChecked(current=>event.target.checked?[...new Set([...current,String(company.id)])]:current.filter(id=>id!==String(company.id)))} className="mt-1 h-4 w-4"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><Link href={`/companies/${company.id}`} className="font-bold">{safe(company.company_name)}</Link><p className="text-xs text-[#75664d]">{SEGMENT_LABELS[intelligence.segment]} · أولوية {safe(company.priority) || 'C'}</p></div><span className={`crm-chip ${contact&&safe(contact.email)?'status-success':contact?'status-warning':'status-danger'}`}>{contact&&safe(contact.email)?'جاهز للبريد':contact?'الشخص موثق بلا بريد':'الشخص مفقود'}</span></div><p className="mt-3 text-sm"><b>الهدف:</b> {safe(company.business_angle) || intelligence.angle}</p><p className="text-sm"><b>الدور المستهدف:</b> {safe(company.recommended_role) || intelligence.role}</p>{contact?<p className="mt-2 text-xs text-[#75664d]">{safe(contact.full_name||contact.name)} · {safe(contact.position||contact.department)} · {safe(contact.email)||'لا يوجد بريد مباشر'}</p>:null}<div className="mt-3 flex gap-2"><button onClick={() => open(company)} className="btn-primary">إعداد مسودة فردية</button><Link href={`/research?tab=manual&company_id=${company.id}`} className="btn-ghost">استكمال الشخص</Link></div></div></div></article>; })}</div>
    <div className="flex justify-between text-sm"><span>صفحة {page} من {pages} · {rows.length} شركة</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="btn-ghost">السابق</button><button disabled={page >= pages} onClick={() => setPage(value => value + 1)} className="btn-ghost">التالي</button></div></div>
    {selected && <div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-3"><div className="max-h-[94vh] w-full max-w-7xl overflow-auto rounded-2xl bg-white p-5"><div className="flex justify-between"><div><h3 className="font-bold">محرر الرسالة — {safe(selected.company_name)}</h3><p className="text-xs text-[#75664d]">مساحة عريضة لمراجعة النص العربي قبل الاعتماد.</p></div><button onClick={() => setSelected(null)} className="btn-ghost">إغلاق</button></div>{selectedStrategy && <div className="mt-3 grid gap-2 rounded-xl bg-[#f8f1e4] p-3 text-xs sm:grid-cols-3"><span><b>الهدف:</b> {selectedStrategy.objective}</span><span><b>الدور:</b> {selectedStrategy.targetRole}</span><span><b>مرحلة العلاقة:</b> {selectedStrategy.relationshipStage}</span><span className="sm:col-span-3"><b>السياق:</b> {selectedStrategy.contextSummary}</span></div>}<div className="mt-4 grid gap-2 sm:grid-cols-4"><select value={language} onChange={event => setLanguage(event.target.value as typeof language)} className="rounded-xl border p-2"><option value="ARABIC">العربية</option><option value="ENGLISH">English</option></select><select value={kind} onChange={event => setKind(event.target.value as MessageType)} className="rounded-xl border p-2">{MESSAGE_TYPES.map(value => <option key={value}>{value}</option>)}</select><select value={style} onChange={event => setStyle(event.target.value as MessageStyle)} className="rounded-xl border p-2">{MESSAGE_STYLES.map(value => <option key={value} value={value}>{styleLabels[value]}</option>)}</select><select value={channel} onChange={event => setChannel(event.target.value as UiChannel)} className="rounded-xl border p-2"><option>Email</option><option>LinkedIn</option><option>WhatsApp</option><option>Call</option></select></div><button onClick={() => setBody(generatedFor(selected).body)} className="btn-secondary mt-3">إعادة الصياغة</button><textarea value={body} onChange={event => setBody(event.target.value)} dir={language === 'ENGLISH' ? 'ltr' : 'rtl'} className="mt-3 min-h-[480px] w-full rounded-xl border p-5 text-[16px] leading-9"/><div className="mt-3 flex flex-wrap items-center gap-2">{quality && <><span className={`crm-chip ${quality.score >= 78 ? 'status-success' : quality.score >= 65 ? 'status-warning' : 'status-danger'}`}>الجودة {quality.score}/100</span><span className="crm-chip status-neutral">التخصيص Level {personalization}</span>{quality.duplicateSimilarity >= 82 && <span className="crm-chip status-danger">تشابه {quality.duplicateSimilarity}%</span>}<span className="text-xs">{quality.warnings.join('، ') || 'صياغة مخصصة وآمنة'}</span></>}<button onClick={() => void navigator.clipboard.writeText(body)} className="btn-ghost mr-auto">نسخ</button><button onClick={() => void save()} className="btn-primary">حفظ للمراجعة</button></div></div></div>}
  </section>;
}
