'use client';
import { useMemo,useState } from 'react';
import Link from 'next/link';
import { businessAngle,generateMessage,messageQuality,MESSAGE_STYLES,MESSAGE_TYPES,type MessageStyle,type MessageType } from '../lib/intelligence/core';
import { isVerifiedDecisionMaker } from '../lib/domain/business';
import { simpleCrud,type SimpleRow } from '../lib/supabase/simple-crud';
const safe=(v:unknown)=>String(v??'').trim();
const styles:Record<string,string>={DIRECT:'مباشرة',RELATIONSHIP:'بناء علاقة',OPPORTUNITY_LED:'مرتبطة بفرصة'};

export function OutreachStrategyWorkspace({companies,contacts,messages,onSaved}:{companies:SimpleRow[];contacts:SimpleRow[];messages:SimpleRow[];onSaved:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<SimpleRow|null>(null),[language,setLanguage]=useState<'ARABIC'|'ENGLISH'>('ARABIC'),[style,setStyle]=useState<MessageStyle>('DIRECT'),[kind,setKind]=useState<MessageType>('INITIAL_INTRODUCTION'),[channel,setChannel]=useState<'Email'|'LinkedIn'|'WhatsApp'|'Call'>('Email'),[body,setBody]=useState(''),[error,setError]=useState('');
 const rows=useMemo(()=>companies.filter(c=>!c.archived_at&&(!query||`${safe(c.company_name)} ${safe(c.sector)} ${safe(c.target_segment)}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>safe(a.priority).localeCompare(safe(b.priority))||Number(b.lead_score??0)-Number(a.lead_score??0)),[companies,query]);
 const visible=rows.slice((page-1)*20,page*20),pages=Math.max(1,Math.ceil(rows.length/20));
 const compose=(company:SimpleRow,nextLanguage=language,nextStyle=style,nextKind=kind,nextChannel=channel)=>{const intel=businessAngle(company),contact=contacts.find(c=>c.company_id===company.id&&isVerifiedDecisionMaker(c));return generateMessage({companyName:safe(company.company_name),recipientName:safe(contact?.full_name||contact?.name),segment:intel.segment,angle:safe(company.business_angle)||intel.angle,role:safe(company.recommended_role)||intel.role,language:nextLanguage,style:nextStyle,type:nextKind,channel:nextChannel})};
 const open=(company:SimpleRow)=>{const intel=businessAngle(company),nextLanguage=safe(company.recommended_language)==='ENGLISH'?'ENGLISH':'ARABIC';setSelected(company);setLanguage(nextLanguage);setStyle(intel.style);setKind(intel.type);setChannel('Email');setBody(compose(company,nextLanguage,intel.style,intel.type,'Email'));setError('')};
 const quality=selected?messageQuality(body,{companyName:safe(selected.company_name),angle:safe(selected.business_angle)||businessAngle(selected).angle,channel},messages.map(m=>safe(m.body))):null;
 const save=async()=>{if(!selected||!quality)return;if(messages.length&&!Object.hasOwn(messages[0],'quality_score')){setError('تخزين V5 غير مفعّل بعد؛ يجب تطبيق migration الآمنة أولاً.');return}if(quality.score<65){setError('الجودة أقل من 65. خصص الرسالة وأضف CTA واضحاً.');return}const contact=contacts.find(c=>c.company_id===selected.id&&isVerifiedDecisionMaker(c));await simpleCrud.create('messages',{company_id:selected.id,company_name:safe(selected.company_name),contact_id:contact?.id??null,recipient:safe(contact?.full_name||contact?.name),channel,subject:language==='ARABIC'?`تواصل مهني مع ${safe(selected.company_name)}`:`Business introduction — ${safe(selected.company_name)}`,body,status:'Draft',draft_classification:contact?'PERSONALIZED':'PREPARATION',language,message_type:kind,message_style:style,quality_score:quality.score,quality_status:quality.status,quality_issues:quality.issues,duplicate_similarity:quality.maxSimilarity});setSelected(null);await onSaved()};
 return <section className="space-y-3"><div className="crm-card flex gap-2 p-3"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="ابحث بالشركة أو القطاع أو الفئة" className="w-full rounded-xl border p-2"/><span className="crm-chip status-neutral">{rows.length}</span></div><div className="grid gap-3 md:grid-cols-2">{visible.map(company=>{const intel=businessAngle(company),contact=contacts.find(c=>c.company_id===company.id&&isVerifiedDecisionMaker(c));return <article key={company.id} className="crm-card p-4"><div className="flex justify-between gap-2"><div><Link href={`/companies/${company.id}`} className="font-bold">{safe(company.company_name)}</Link><p className="text-xs text-[#75664d]">{intel.segment} · أولوية {safe(company.priority)||'C'}</p></div><span className={`crm-chip ${contact?'status-success':'status-warning'}`}>{contact?'جهة موثقة':'الشخص مفقود'}</span></div><p className="mt-3 text-sm"><b>الزاوية:</b> {safe(company.business_angle)||intel.angle}</p><p className="text-sm"><b>الدور:</b> {safe(company.recommended_role)||intel.role}</p><div className="mt-3 flex gap-2"><button onClick={()=>open(company)} className="btn-primary">إعداد مسودة</button><Link href={`/research?tab=manual&company_id=${company.id}`} className="btn-ghost">بحث</Link></div></article>})}</div><div className="flex justify-between text-sm"><span>صفحة {page} من {pages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)} className="btn-ghost">السابق</button><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)} className="btn-ghost">التالي</button></div></div>
 {selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-3"><div className="max-h-[94vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-5"><div className="flex justify-between"><div><h3 className="font-bold">محرر الرسالة — {safe(selected.company_name)}</h3><p className="text-xs text-[#75664d]">مسودة فقط؛ الإرسال الخارجي معطّل.</p></div><button onClick={()=>setSelected(null)} className="btn-ghost">إغلاق</button></div><div className="mt-4 grid gap-2 sm:grid-cols-4"><select value={language} onChange={e=>setLanguage(e.target.value as typeof language)} className="rounded-xl border p-2"><option value="ARABIC">العربية</option><option value="ENGLISH">English</option></select><select value={kind} onChange={e=>setKind(e.target.value as MessageType)} className="rounded-xl border p-2">{MESSAGE_TYPES.map(x=><option key={x}>{x}</option>)}</select><select value={style} onChange={e=>setStyle(e.target.value as MessageStyle)} className="rounded-xl border p-2">{MESSAGE_STYLES.map(x=><option key={x} value={x}>{styles[x]}</option>)}</select><select value={channel} onChange={e=>setChannel(e.target.value as typeof channel)} className="rounded-xl border p-2"><option>Email</option><option>LinkedIn</option><option>WhatsApp</option><option>Call</option></select></div><button onClick={()=>setBody(compose(selected))} className="btn-secondary mt-3">إعادة الصياغة</button><textarea value={body} onChange={e=>setBody(e.target.value)} dir={language==='ENGLISH'?'ltr':'rtl'} className="mt-3 min-h-56 w-full rounded-xl border p-4 leading-7"/><div className="mt-3 flex flex-wrap items-center gap-2">{quality&&<><span className={`crm-chip ${quality.score>=80?'status-success':quality.score>=65?'status-warning':'status-danger'}`}>الجودة {quality.score}/100</span>{quality.maxSimilarity>=82&&<span className="crm-chip status-danger">تشابه {quality.maxSimilarity}%</span>}<span className="text-xs">{quality.issues.join('، ')||'صياغة مخصصة'}</span></>}<button onClick={()=>void navigator.clipboard.writeText(body)} className="btn-ghost mr-auto">نسخ</button><button onClick={()=>void save()} className="btn-primary">حفظ للمراجعة</button></div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div></div>}
 </section>;
}
