'use client';
/* eslint-disable react-hooks/exhaustive-deps -- load is intentionally keyed by route tab and page. */

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { CRMPage } from './crm-shell';
import { companyOutreachState, isVerifiedDecisionMaker } from '../lib/domain/business';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';

type Tab='drafts'|'review'|'ready'|'history';
const tabs:Array<[Tab,string]>=[['drafts','المسودات'],['review','المراجعة'],['ready','الجاهز'],['history','سجل التواصل']];
const safe=(value:unknown)=>String(value??'').trim();

export function OutreachWorkspace(){
  const params=useSearchParams(),tab=(tabs.some(([id])=>id===params.get('tab'))?params.get('tab'):'review') as Tab;
  const [messages,setMessages]=useState<SimpleRow[]>([]),[companies,setCompanies]=useState<SimpleRow[]>([]),[contacts,setContacts]=useState<SimpleRow[]>([]),[events,setEvents]=useState<SimpleRow[]>([]);
  const [page,setPage]=useState(1),[total,setTotal]=useState(0),[query,setQuery]=useState(''),[priority,setPriority]=useState('الكل'),[selected,setSelected]=useState<{company:SimpleRow;draft?:SimpleRow}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [event,setEvent]=useState({contact_id:'',channel:'Email',direction:'OUTBOUND',recipient:'',occurred_at:new Date().toISOString().slice(0,16),status:'COMPLETED',outcome:'',notes:'',evidence_reference:'',next_action:'',next_action_date:''});
  const load=async()=>{setLoading(true);try{const[m,c,p,e]=await Promise.all([simpleCrud.page('messages',page,25,{order:'created_at'}),simpleCrud.page('companies',1,500,{order:'company_name',ascending:true}),simpleCrud.page('contacts',1,500,{order:'created_at'}),simpleCrud.page('communication_events',tab==='history'?page:1,tab==='history'?25:500,{order:'occurred_at'})]);setMessages(m.rows);setTotal(tab==='history'?e.count:m.count);setCompanies(c.rows);setContacts(p.rows);setEvents(e.rows);}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحميل مساحة التواصل.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[page,tab]);
  const enriched=useMemo(()=>messages.map(draft=>{const company=companies.find(c=>c.id===draft.company_id);const contact=contacts.find(c=>c.id===draft.contact_id);return{draft,company,contact,state:company?companyOutreachState(company,contacts,messages,events):'CONTACT_NEEDED'}}).filter(item=>item.company),[companies,contacts,events,messages]);
  const visible=enriched.filter(item=>{const text=`${safe(item.company?.company_name)} ${safe(item.draft.subject)} ${safe(item.contact?.full_name||item.contact?.name)}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(priority==='الكل'||safe(item.company?.priority)===priority)&&(tab==='drafts'||tab==='review'?[tab==='drafts'?'Draft':'Approved'].includes(safe(item.draft.status)):tab==='ready'?['DRAFT_READY','APPROVED'].includes(item.state):true)});
  const approve=async(item:(typeof enriched)[number])=>{if(!item.contact||!isVerifiedDecisionMaker(item.contact)){setError('لا يمكن اعتماد المسودة كجاهزة دون صانع قرار موثق. يمكن إبقاؤها PREPARATION / GENERIC DRAFT.');return}await simpleCrud.update('messages',item.draft.id,{status:'Approved',draft_classification:'PERSONALIZED',approved_at:new Date().toISOString()});setNotice('تم اعتماد المسودة للشخص الموثق.');await load()};
  const openEvent=(item:(typeof enriched)[number])=>{const recipient=safe(item.contact?.full_name||item.contact?.name||item.company?.general_email||item.company?.general_phone);setEvent({...event,contact_id:safe(item.contact?.id),recipient,outcome:'',notes:'',evidence_reference:'',next_action:'',next_action_date:''});setSelected({company:item.company!,draft:item.draft})};
  const recordEvent=async(formEvent:FormEvent)=>{formEvent.preventDefault();if(!selected)return;if(!event.recipient.trim()){setError('يجب تحديد المستلم أو القناة العامة.');return}try{const created=await simpleCrud.create('communication_events',{company_id:selected.company.id,contact_id:event.contact_id||null,channel:event.channel,direction:event.direction,recipient:event.recipient,occurred_at:new Date(event.occurred_at).toISOString(),status:event.status,outcome:event.outcome,notes:event.notes,evidence_reference:event.evidence_reference,next_action:event.next_action,next_action_date:event.next_action_date||null});if(selected.draft&&event.direction==='OUTBOUND')await simpleCrud.update('messages',selected.draft.id,{status:'Contacted',sent_at:new Date(event.occurred_at).toISOString()});if(event.next_action&&event.next_action_date)await simpleCrud.create('follow_ups',{company_id:selected.company.id,company_name:safe(selected.company.company_name),contact_id:event.contact_id||null,contact_person:event.recipient,follow_up_type:event.channel,date:event.next_action_date,time:'09:00',priority:safe(selected.company.priority)==='A'?'High':'Medium',status:'Pending',subject:event.next_action,next_action:event.next_action});setNotice(`تم تسجيل ${event.direction==='INBOUND'?'رد وارد':'تواصل صادر'} كحدث موثق.`);setSelected(null);setEvents(rows=>[created,...rows]);await load()}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تسجيل التواصل.')}};
  const totalPages=Math.max(1,Math.ceil(total/25));
  return <CRMPage title="التواصل" description="المسودات الحالية Preparation فقط حتى ترتبط بشخص موثّق. Contacted وReplied ينتجان حصراً من أحداث التواصل.">
    <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-[#f7efdf] p-2">{tabs.map(([id,label])=><Link key={id} href={`/outreach?tab=${id}`} className={`shrink-0 rounded-xl px-4 py-2 text-sm font-bold ${tab===id?'bg-[#2f2417] text-white':'bg-white'}`}>{label}</Link>)}</div>
    {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
    {tab!=='history'&&<div className="crm-card grid gap-2 p-3 sm:grid-cols-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالشركة أو المستلم" className="rounded-xl border p-2"/><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border p-2"><option>الكل</option><option>A</option><option>B</option><option>C</option></select><div className="rounded-xl bg-[#f7efdf] p-2 text-center text-sm">{total} مسودة محفوظة</div></div>}
    {loading?<div className="crm-empty animate-pulse">جارٍ تحميل التواصل...</div>:tab==='history'?<div className="grid gap-2">{events.map(row=><article key={row.id} className="crm-card p-3"><div className="flex justify-between gap-2"><strong>{safe(companies.find(c=>c.id===row.company_id)?.company_name)}</strong><span className={`crm-chip ${row.direction==='INBOUND'?'bg-blue-100 text-blue-800':'bg-emerald-100 text-emerald-800'}`}>{safe(row.direction)}</span></div><p className="mt-1 text-sm">{safe(row.recipient)} · {safe(row.channel)} · {safe(row.outcome)}</p><p className="text-xs text-[#75664d]">{safe(row.occurred_at)} · {safe(row.notes)}</p></article>)}{!events.length&&<div className="crm-empty">لا توجد أحداث تواصل موثقة بعد.</div>}</div>:<div className="grid gap-3">{visible.map(item=><article key={item.draft.id} className="crm-card p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><Link href={`/companies/${item.company!.id}`} className="font-bold">{safe(item.company?.company_name)}</Link><p className="text-xs text-[#75664d]">Priority {safe(item.company?.priority)} · {safe(item.contact?.full_name||item.contact?.name)||'قناة عامة — لا يوجد صانع قرار موثق'}</p></div><span className="crm-chip bg-[#f0e3ca]">{item.state}</span></div><p className="mt-2 text-xs text-[#75664d]">{safe(item.draft.channel)} · {safe(item.draft.status)} · {safe(item.draft.draft_classification)||'PREPARATION'}</p><textarea defaultValue={safe(item.draft.body)} onBlur={e=>void simpleCrud.update('messages',item.draft.id,{body:e.target.value})} className="mt-3 min-h-28 w-full rounded-xl border p-3 text-sm"/><div className="mt-3 flex flex-wrap gap-2 text-xs"><button onClick={()=>void navigator.clipboard.writeText(safe(item.draft.body))} className="rounded-lg border px-3 py-2">نسخ</button><button onClick={()=>void approve(item)} className="rounded-lg border px-3 py-2">اعتماد</button><button onClick={()=>openEvent(item)} className="rounded-lg bg-[#2f2417] px-3 py-2 text-white">تسجيل تواصل</button></div></article>)}{!visible.length&&<div className="crm-empty">لا توجد سجلات مطابقة في هذه الصفحة.</div>}</div>}
    <div className="flex items-center justify-between text-sm"><span>صفحة {page} من {totalPages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">السابق</button><button disabled={page>=totalPages} onClick={()=>setPage(v=>v+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">التالي</button></div></div>
    {selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-3"><form onSubmit={recordEvent} className="max-h-[92vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-5"><h3 className="font-bold">تسجيل تواصل — {safe(selected.company.company_name)}</h3>{!event.contact_id&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">قناة عامة — لا يوجد صانع قرار موثق. لن تُصنف الشركة Decision-Maker Ready.</p>}<div className="mt-4 grid gap-3 md:grid-cols-2"><select value={event.contact_id} onChange={e=>{const contact=contacts.find(c=>c.id===e.target.value);setEvent({...event,contact_id:e.target.value,recipient:safe(contact?.full_name||contact?.name)||event.recipient})}} className="rounded-xl border p-2"><option value="">قناة عامة</option>{contacts.filter(c=>c.company_id===selected.company.id).map(c=><option key={c.id} value={c.id}>{safe(c.full_name||c.name)}</option>)}</select><select value={event.direction} onChange={e=>setEvent({...event,direction:e.target.value})} className="rounded-xl border p-2"><option>OUTBOUND</option><option>INBOUND</option></select><select value={event.channel} onChange={e=>setEvent({...event,channel:e.target.value})} className="rounded-xl border p-2"><option>Email</option><option>Phone</option><option>WhatsApp</option><option>LinkedIn</option><option>Meeting</option><option>Visit</option></select><input required value={event.recipient} onChange={e=>setEvent({...event,recipient:e.target.value})} placeholder="الشخص/المستلم *" className="rounded-xl border p-2"/><input required type="datetime-local" value={event.occurred_at} onChange={e=>setEvent({...event,occurred_at:e.target.value})} className="rounded-xl border p-2"/><input value={event.outcome} onChange={e=>setEvent({...event,outcome:e.target.value})} placeholder="النتيجة" className="rounded-xl border p-2"/><input value={event.evidence_reference} onChange={e=>setEvent({...event,evidence_reference:e.target.value})} placeholder="Evidence / Reference" className="rounded-xl border p-2 md:col-span-2"/><textarea value={event.notes} onChange={e=>setEvent({...event,notes:e.target.value})} placeholder="ملاحظة" className="rounded-xl border p-2 md:col-span-2"/><input value={event.next_action} onChange={e=>setEvent({...event,next_action:e.target.value})} placeholder="الإجراء التالي" className="rounded-xl border p-2"/><input type="date" value={event.next_action_date} onChange={e=>setEvent({...event,next_action_date:e.target.value})} className="rounded-xl border p-2"/></div><div className="mt-4 flex gap-2"><button className="rounded-xl bg-[#2f2417] px-5 py-2 text-white">حفظ الحدث</button><button type="button" onClick={()=>setSelected(null)} className="rounded-xl border px-5 py-2">إلغاء</button></div></form></div>}
  </CRMPage>;
}
