'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { CRMPage } from './crm-shell';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';
const safe=(v:unknown)=>String(v??'').trim();
const TYPES=[['ENGINEERING_CONSULTANT','استشاري هندسي'],['MAIN_CONTRACTOR_REFERRER','مقاول / مُحيل'],['SUPPLIER_REFERRER','مورد / مُحيل'],['OTHER_REFERRER','شريك إحالة آخر']] as const;
export function PartnersWorkspace(){
 const [partners,setPartners]=useState<SimpleRow[]>([]),[referrals,setReferrals]=useState<SimpleRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [form,setForm]=useState({partner_name:'',partner_type:'ENGINEERING_CONSULTANT',relationship_strength:'0',notes:''});
 const load=async()=>{setLoading(true);try{const[p,r]=await Promise.all([simpleCrud.list('referral_partners'),simpleCrud.list('referrals')]);setPartners(p);setReferrals(r)}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحميل الشركاء.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const stats=useMemo(()=>({partners:partners.length,introductions:referrals.filter(r=>r.status==='INTRODUCED').length,meetings:referrals.filter(r=>r.status==='MEETING').length,rfqs:referrals.filter(r=>r.status==='RFQ').length,wins:referrals.filter(r=>r.status==='WON').length}),[partners,referrals]);
 const add=async(e:FormEvent)=>{e.preventDefault();if(!form.partner_name.trim())return;try{await simpleCrud.create('referral_partners',{partner_name:form.partner_name.trim(),partner_type:form.partner_type,relationship_strength:Number(form.relationship_strength),notes:form.notes});setForm({partner_name:'',partner_type:'ENGINEERING_CONSULTANT',relationship_strength:'0',notes:''});setNotice('تمت إضافة شريك الإحالة. لا يُحسب أي Referral حتى يتم تسجيله فعلياً.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'تعذر إضافة الشريك.')}};
 return <CRMPage title="الشركاء" description="قناة الإحالات والتأثير: الاستشاريون والشركاء الذين قد يفتحون باباً لا يشتروه هم أنفسهم.">
  {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
  <div className="grid gap-3 sm:grid-cols-5">{[['الشركاء',stats.partners],['Introductions',stats.introductions],['Meetings',stats.meetings],['RFQs',stats.rfqs],['Won',stats.wins]].map(([label,value])=><div key={label} className="crm-card p-4"><p className="text-xs text-[#75664d]">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>
  <form onSubmit={add} className="crm-card grid gap-3 p-4 md:grid-cols-4"><input value={form.partner_name} onChange={e=>setForm({...form,partner_name:e.target.value})} placeholder="اسم الشريك الحقيقي" className="rounded-xl border p-2"/><select value={form.partner_type} onChange={e=>setForm({...form,partner_type:e.target.value})} className="rounded-xl border p-2">{TYPES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input type="number" min="0" max="100" value={form.relationship_strength} onChange={e=>setForm({...form,relationship_strength:e.target.value})} className="rounded-xl border p-2" placeholder="قوة العلاقة 0-100"/><button className="btn-primary">إضافة شريك</button><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات موثقة عن العلاقة" className="rounded-xl border p-2 md:col-span-4"/></form>
  {loading?<div className="crm-empty animate-pulse">جارٍ التحميل…</div>:<div className="grid gap-3">{partners.map(p=>{const own=referrals.filter(r=>r.partner_id===p.id);return <article key={p.id} className="crm-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{safe(p.partner_name)}</strong><p className="mt-1 text-xs text-[#75664d]">{TYPES.find(([v])=>v===p.partner_type)?.[1]||safe(p.partner_type)} · قوة العلاقة {Number(p.relationship_strength||0)}/100</p><p className="mt-2 text-sm">{safe(p.notes)||'لا توجد ملاحظات بعد.'}</p></div><div className="text-left text-xs"><p>{own.length} إحالة مسجلة</p><p>{own.filter(r=>r.status==='MEETING').length} اجتماع</p><p>{own.filter(r=>r.status==='RFQ').length} RFQ</p></div></div></article>})}{!partners.length&&<div className="crm-empty">لا توجد شراكات إحالة مسجلة بعد. أضف فقط العلاقات الحقيقية التي تعرفها فعلاً.</div>}</div>}
  <div className="crm-card p-4 text-sm"><b>مبدأ القياس:</b> لا نعتبر الاستشاري Opportunity. نسجل الإحالة منه، ثم نربطها بالشركة أو المشروع الذي دخلنا إليه فعلياً. <Link href="/companies" className="mr-1 underline">العودة للشركات</Link></div>
 </CRMPage>;
}
