'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { CRMPage } from './crm-shell';
import { OPPORTUNITY_STAGES, canonicalOpportunityStage } from '../lib/domain/business';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';
import { dealCoach, opportunityHealth } from '../lib/intelligence/v6';

const safe=(value:unknown)=>String(value??'').trim();
const stageLabel:Record<string,string>={IDENTIFIED:'مستهدفة',QUALIFIED:'مؤهلة',RFQ_RECEIVED:'طلب عرض مستلم',PROPOSAL:'عرض مقدم',NEGOTIATION:'تفاوض',WON:'فوز',LOST:'خسارة'};
type Tab='opportunities'|'rfqs'|'proposals'|'closed';
const tabs:Array<[Tab,string]>=[['opportunities','الفرص'],['rfqs','طلبات العروض'],['proposals','العروض'],['closed','فوز / خسارة']];

export function PipelineWorkspace(){
  const params=useSearchParams(), tab=(tabs.some(([id])=>id===params.get('tab'))?params.get('tab'):'opportunities') as Tab;
  const [rows,setRows]=useState<SimpleRow[]>([]),[companies,setCompanies]=useState<SimpleRow[]>([]),[contacts,setContacts]=useState<SimpleRow[]>([]),[events,setEvents]=useState<SimpleRow[]>([]),[followUps,setFollowUps]=useState<SimpleRow[]>([]);
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<SimpleRow|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [form,setForm]=useState({company_id:'',contact_id:'',source_communication_event_id:'',title:'',stage:'IDENTIFIED',value:'',next_action:'',next_action_date:'',owner:'',notes:'',source:''});
  const load=async()=>{setLoading(true);try{const[a,b,c,d,e]=await Promise.all([simpleCrud.page('opportunities',1,500,{order:'updated_at'}),simpleCrud.page('companies',1,500,{order:'company_name',ascending:true}),simpleCrud.page('contacts',1,500,{order:'created_at'}),simpleCrud.page('communication_events',1,500,{order:'occurred_at'}),simpleCrud.page('follow_ups',1,1000,{order:'date'})]);setRows(a.rows);setCompanies(b.rows);setContacts(c.rows);setEvents(d.rows);setFollowUps(e.rows);}catch(reason){setError(reason instanceof Error?reason.message:'تعذر تحميل مسار الفرص.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>rows.filter(row=>!row.archived_at).filter(row=>{const stage=canonicalOpportunityStage(row.stage);return tab==='rfqs'?stage==='RFQ_RECEIVED':tab==='proposals'?['PROPOSAL','NEGOTIATION'].includes(stage):tab==='closed'?['WON','LOST'].includes(stage):!['RFQ_RECEIVED','PROPOSAL','NEGOTIATION','WON','LOST'].includes(stage)}),[rows,tab]);
  const edit=(row:SimpleRow)=>{setEditing(row);setForm({company_id:safe(row.company_id),contact_id:safe(row.contact_id),source_communication_event_id:safe(row.source_communication_event_id),title:safe(row.title),stage:canonicalOpportunityStage(row.stage),value:safe(row.value),next_action:safe(row.next_action),next_action_date:safe(row.next_action_date),owner:safe(row.owner),notes:safe(row.notes),source:safe(row.source)});setOpen(true)};
  const fresh=()=>{setEditing(null);setForm({company_id:'',contact_id:'',source_communication_event_id:'',title:'',stage:'IDENTIFIED',value:'',next_action:'',next_action_date:'',owner:'',notes:'',source:''});setOpen(true)};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.source_communication_event_id&&!form.source.trim()){setError('يجب توثيق سبب تجاري أو حدث تواصل مصدر للفرصة.');return}setError('');try{const health=opportunityHealth({stage:form.stage,nextAction:form.next_action,dueAt:form.next_action_date});const payload={...form,company_name:safe(companies.find(c=>c.id===form.company_id)?.company_name),contact_id:form.contact_id||null,source_communication_event_id:form.source_communication_event_id||null,value:form.value?Number(form.value):null,next_action_date:form.next_action_date||null,health_status:health.health,health_reason:health.reason,deal_next_step:form.next_action,deal_due_date:form.next_action_date||null};if(editing)await simpleCrud.update('opportunities',editing.id,payload);else await simpleCrud.create('opportunities',payload);setNotice('تم حفظ الفرصة مع السبب والإجراء التالي وحالة الصحة.');setOpen(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:'تعذر حفظ الفرصة.')}};
  const close=async(row:SimpleRow,stage:'WON'|'LOST')=>{await simpleCrud.update('opportunities',row.id,{stage,closed_at:new Date().toISOString()});setNotice(stage==='WON'?'تم إغلاق الفرصة كفوز.':'تم إغلاق الفرصة كخسارة.');await load()};
  const archive=async(row:SimpleRow)=>{if(!window.confirm('أرشفة الفرصة مع الاحتفاظ بالتاريخ؟'))return;await simpleCrud.update('opportunities',row.id,{archived_at:new Date().toISOString()});setNotice('تمت الأرشفة دون حذف السجل.');await load()};
  return <CRMPage title="مسار الفرص" description="الفرصة تبدأ بسبب تجاري موثق، وترتبط بحدث التواصل والمتابعة والإجراء التالي حتى الفوز أو الخسارة." action={<button onClick={fresh} className="btn-primary">إضافة فرصة موثقة</button>}>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-[#f7efdf] p-2">{tabs.map(([id,label])=><Link key={id} href={`/pipeline?tab=${id}`} className={`shrink-0 rounded-xl px-4 py-2 text-sm font-bold ${tab===id?'bg-[#2f2417] text-white':'bg-white'}`}>{label}</Link>)}</div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="crm-kpi min-h-0 p-4"><p className="text-xs text-[#75664d]">فرص نشطة</p><strong className="mt-1 block text-2xl">{rows.filter(row=>!row.archived_at&&!['WON','LOST'].includes(canonicalOpportunityStage(row.stage))).length}</strong></div><div className="crm-kpi min-h-0 p-4"><p className="text-xs text-[#75664d]">متابعات مرتبطة</p><strong className="mt-1 block text-2xl">{followUps.filter(row=>rows.some(opp=>opp.company_id===row.company_id)&&!['Completed','Cancelled'].includes(safe(row.status))).length}</strong></div><div className="crm-kpi min-h-0 p-4"><p className="text-xs text-[#75664d]">أحداث مصدر</p><strong className="mt-1 block text-2xl">{events.length}</strong></div><div className="crm-kpi min-h-0 p-4"><p className="text-xs text-[#75664d]">مراحل مستخدمة</p><strong className="mt-1 block text-2xl">{new Set(rows.map(row=>stageLabel[canonicalOpportunityStage(row.stage)])).size}</strong></div></div>
    {error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{notice}</p>}
    {loading?<div className="crm-empty animate-pulse">جارٍ تحميل الفرص...</div>:<div className="grid gap-3">{visible.map(row=>{const company=companies.find(c=>c.id===row.company_id);const coach=dealCoach({company:company??{},contacts,events,opportunities:[row]});return <article key={row.id} className="crm-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{safe(row.title)}</strong><p className="text-xs text-[#75664d]">{safe(company?.company_name)} · {canonicalOpportunityStage(row.stage)} · {row.value==null?'قيمة غير محددة':safe(row.value)}</p></div><div className="flex gap-2"><span className="crm-chip bg-[#f0e3ca]">{canonicalOpportunityStage(row.stage)}</span><span className={`crm-chip ${coach.relationshipHealth.health==='HEALTHY'?'status-success':coach.relationshipHealth.health==='AT_RISK'?'status-danger':'status-warning'}`}>{coach.relationshipHealth.health}</span></div></div><p className="mt-3 text-sm"><b>الإجراء التالي:</b> {safe(row.next_action)} {safe(row.next_action_date)&&`— ${safe(row.next_action_date)}`}</p><div className="mt-3 grid gap-2 rounded-xl bg-[#f8f1e4] p-3 text-xs md:grid-cols-3"><p><b>الوضع الحالي:</b> {coach.currentSituation}</p><p><b>النقص:</b> {coach.missingInformation.join('، ')||'لا يوجد'}</p><p><b>المخاطر:</b> {coach.risks.join('، ')||'لا توجد مخاطر موثقة'}</p></div><p className="mt-2 text-xs text-[#75664d]">المصدر: {safe(row.source)||'Communication Event'} · المسؤول: {safe(row.owner)||'غير محدد'}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><button onClick={()=>edit(row)} className="rounded-lg border px-3 py-2">تعديل</button><button onClick={()=>void close(row,'WON')} className="rounded-lg bg-emerald-700 px-3 py-2 text-white">Close Won</button><button onClick={()=>void close(row,'LOST')} className="rounded-lg bg-stone-700 px-3 py-2 text-white">Close Lost</button><button onClick={()=>void archive(row)} className="rounded-lg border px-3 py-2 text-red-700">أرشفة</button></div></article>})}{!visible.length&&<div className="crm-empty">لا توجد سجلات في هذه المرحلة.</div>}</div>}
    {open&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-3"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5"><h3 className="font-bold">{editing?'تعديل الفرصة':'فرصة جديدة'}</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><select required value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value,contact_id:'',source_communication_event_id:''})} className="rounded-xl border p-2"><option value="">الشركة *</option>{companies.map(c=><option key={c.id} value={c.id}>{safe(c.company_name)}</option>)}</select><select value={form.contact_id} onChange={e=>setForm({...form,contact_id:e.target.value})} className="rounded-xl border p-2"><option value="">جهة الاتصال</option>{contacts.filter(c=>c.company_id===form.company_id).map(c=><option key={c.id} value={c.id}>{safe(c.full_name||c.name)}</option>)}</select><select value={form.source_communication_event_id} onChange={e=>setForm({...form,source_communication_event_id:e.target.value})} className="rounded-xl border p-2 md:col-span-2"><option value="">لا يوجد حدث مرتبط — اكتب السبب أدناه</option>{events.filter(e=>e.company_id===form.company_id).map(e=><option key={e.id} value={e.id}>{safe(e.direction)} · {safe(e.channel)} · {safe(e.outcome)}</option>)}</select><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="عنوان الفرصة *" className="rounded-xl border p-2"/><select required value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} className="rounded-xl border p-2">{OPPORTUNITY_STAGES.map(s=><option key={s}>{s}</option>)}</select><input type="number" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder="القيمة التقديرية — اختيارية" className="rounded-xl border p-2"/><input required value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})} placeholder="الإجراء التالي *" className="rounded-xl border p-2"/><input required type="date" value={form.next_action_date} onChange={e=>setForm({...form,next_action_date:e.target.value})} className="rounded-xl border p-2"/><input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} placeholder="المسؤول" className="rounded-xl border p-2"/><input value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="السبب/المصدر التجاري" className="rounded-xl border p-2 md:col-span-2"/><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات" className="rounded-xl border p-2 md:col-span-2"/></div><div className="mt-4 flex gap-2"><button className="rounded-xl bg-[#2f2417] px-5 py-2 text-white">حفظ</button><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-2">إلغاء</button></div></form></div>}
  </CRMPage>;
}
