'use client';
import {useEffect,useMemo,useState}from'react';
import Link from'next/link';
import {CRMPage}from'./crm-shell';
import {simpleCrud,type SimpleRow}from'../lib/supabase/simple-crud';
import {relationshipLabel,strongestEdges}from'../lib/acquisition-v3/core';

const s=(v:unknown)=>String(v??'').trim();

export function RelationshipIntelligence(){
 const[data,setData]=useState<Record<string,SimpleRow[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[show,setShow]=useState<'VERIFIED'|'ALL'>('VERIFIED');
 const[notice,setNotice]=useState('');
 const[form,setForm]=useState({from_company_id:'',to_company_id:'',relationship_type:'KNOWS',strength:50,evidence_url:'',verification_status:'needs_research',notes:''});
 useEffect(()=>{void(async()=>{try{const specs:[string,number,string][]=[['relationship_edges',3000,'updated_at'],['companies',2500,'company_name'],['contacts',4000,'name'],['projects',1500,'updated_at']];const rows=await Promise.all(specs.map(async([t,z,o])=>[t,(await simpleCrud.page(t,1,z,{order:o})).rows]as const));setData(Object.fromEntries(rows))}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل Relationship Intelligence.')}finally{setLoading(false)}})()},[]);
 const edges=data.relationship_edges??[],companies=data.companies??[],contacts=data.contacts??[],projects=data.projects??[];
 const companyById=useMemo(()=>new Map(companies.map(x=>[s(x.id),x])),[companies]);
 const contactById=useMemo(()=>new Map(contacts.map(x=>[s(x.id),x])),[contacts]);
 const projectById=useMemo(()=>new Map(projects.map(x=>[s(x.id),x])),[projects]);
 const label=(companyId:unknown,contactId:unknown)=>s(contactId)?s(contactById.get(s(contactId))?.name)||s(contactById.get(s(contactId))?.position)||'شخص':s(companyById.get(s(companyId))?.company_name)||'شركة';
 const visible=useMemo(()=>show==='ALL'?[...edges].sort((a,b)=>Number(b.strength||0)-Number(a.strength||0)):strongestEdges(edges,1000),[edges,show]);
 const addEdge=async()=>{if(!form.from_company_id||!form.to_company_id){setError('حدد طرفي العلاقة.');return}if(form.from_company_id===form.to_company_id){setError('لا يمكن ربط الشركة بنفسها.');return}try{await simpleCrud.create('relationship_edges',{...form,from_company_id:form.from_company_id,to_company_id:form.to_company_id,from_contact_id:null,to_contact_id:null,project_id:null});setNotice('تم تسجيل العلاقة. تبقى needs_research حتى اعتماد الدليل.');setForm({from_company_id:'',to_company_id:'',relationship_type:'KNOWS',strength:50,evidence_url:'',verification_status:'needs_research',notes:''});const r=await simpleCrud.page('relationship_edges',1,3000,{order:'updated_at'});setData(v=>({...v,relationship_edges:r.rows}))}catch(e){setError(e instanceof Error?e.message:'تعذر تسجيل العلاقة.')}};

 return <CRMPage title="Relationship Intelligence" description="من يعرف من؟ ومن يستطيع أن يفتح لنا باب المشروع؟ العلاقات الموثقة تتحول إلى مسارات دخول قابلة للتنفيذ.">
  {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
  <section className="grid gap-3 md:grid-cols-4"><div className="crm-kpi"><span>العلاقات المسجلة</span><b className="mt-2 block text-3xl">{edges.length}</b></div><div className="crm-kpi"><span>العلاقات الموثقة</span><b className="mt-2 block text-3xl">{edges.filter(x=>s(x.verification_status)==='verified').length}</b></div><div className="crm-kpi"><span>إحالات</span><b className="mt-2 block text-3xl">{edges.filter(x=>s(x.relationship_type)==='REFERRAL'||s(x.relationship_type)==='INTRODUCED_BY').length}</b></div><div className="crm-kpi"><span>مرتبطة بمشروع</span><b className="mt-2 block text-3xl">{edges.filter(x=>s(x.project_id)).length}</b></div></section>
  <section className="crm-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-[var(--nav-accent)]">RELATIONSHIP GRAPH</p><h3 className="text-xl font-bold">أقوى طرق الوصول</h3></div><div className="flex gap-2"><button className={show==='VERIFIED'?'btn-primary':'btn-ghost'} onClick={()=>setShow('VERIFIED')}>الموثقة فقط</button><button className={show==='ALL'?'btn-primary':'btn-ghost'} onClick={()=>setShow('ALL')}>الكل</button></div></div></section>  <section className="crm-card p-4"><div><p className="text-xs font-bold text-[var(--nav-accent)]">ADD RELATIONSHIP</p><h3 className="font-bold">سجل مسار معرفة موثق</h3></div><div className="mt-3 grid gap-2 md:grid-cols-3"><select value={form.from_company_id} onChange={e=>setForm({...form,from_company_id:e.target.value})} className="rounded-xl border p-2"><option value="">من شركة...</option>{companies.map(c=><option value={s(c.id)} key={c.id}>{s(c.company_name)}</option>)}</select><select value={form.relationship_type} onChange={e=>setForm({...form,relationship_type:e.target.value})} className="rounded-xl border p-2"><option>KNOWS</option><option>WORKED_WITH</option><option>CURRENT_PROJECT</option><option>PAST_PROJECT</option><option>REFERRAL</option><option>SUPPLIER_OF</option><option>CONSULTANT_TO</option><option>CONTRACTOR_TO</option><option>CLIENT_OF</option><option>INTRODUCED_BY</option><option>OTHER</option></select><select value={form.to_company_id} onChange={e=>setForm({...form,to_company_id:e.target.value})} className="rounded-xl border p-2"><option value="">إلى شركة...</option>{companies.map(c=><option value={s(c.id)} key={c.id}>{s(c.company_name)}</option>)}</select><label className="text-xs">Strength {form.strength}<input type="range" min="0" max="100" value={form.strength} onChange={e=>setForm({...form,strength:Number(e.target.value)})} className="w-full"/></label><input value={form.evidence_url} onChange={e=>setForm({...form,evidence_url:e.target.value})} placeholder="Evidence URL" className="rounded-xl border p-2"/><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات" className="rounded-xl border p-2"/></div><button onClick={()=>void addEdge()} className="btn-secondary mt-3">حفظ العلاقة</button></section>
  {loading?<div className="crm-empty">جارٍ بناء شبكة العلاقات…</div>:<div className="grid gap-3">{visible.map(edge=>{const project=projectById.get(s(edge.project_id));return <article key={edge.id} className="crm-card p-4"><div className="grid gap-3 lg:grid-cols-[1fr_auto_1fr_.65fr_.8fr] lg:items-center"><div><span className="text-xs text-[#8f96a3]">FROM</span><b className="block text-lg">{label(edge.from_company_id,edge.from_contact_id)}</b></div><div className="text-center"><span className="crm-chip status-neutral">{relationshipLabel(edge)}</span><div className="mt-1 text-xl text-[var(--nav-accent)]">←</div></div><div><span className="text-xs text-[#8f96a3]">TO</span><b className="block text-lg">{label(edge.to_company_id,edge.to_contact_id)}</b></div><div><span className="text-xs text-[#8f96a3]">Strength</span><b className="block text-2xl">{Number(edge.strength||0)}/100</b><small>{s(edge.verification_status)}</small></div><div>{project?<Link href={`/projects/${project.id}`} className="btn-secondary">{s(project.project_name)}</Link>:<span className="text-xs text-[#8f96a3]">غير مرتبطة بمشروع</span>}{s(edge.evidence_url)&&<a href={s(edge.evidence_url)} target="_blank" rel="noreferrer" className="btn-ghost mr-2">الدليل</a>}</div></div></article>})}{!visible.length&&<div className="crm-empty">لم تُسجل علاقات موثقة بعد. العلاقات لا تُستنتج بدون دليل.</div>}</div>}
 </CRMPage>
}
