'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { CRMPage } from './crm-shell';
import { CompanyDiscoveryWorkspace } from './company-discovery-workspace';
import { simpleCrud, type SimpleRow } from '../lib/supabase/simple-crud';

type Tab = 'discovery' | 'enrichment' | 'manual';
const safe = (value: unknown) => String(value ?? '').trim();
const tabs: Array<[Tab, string]> = [['discovery','اكتشاف'],['enrichment','استكمال البيانات'],['manual','قائمة البحث اليدوي']];

export function ResearchWorkspace() {
  const params = useSearchParams();
  const tab = (tabs.some(([id]) => id === params.get('tab')) ? params.get('tab') : 'manual') as Tab;
  const [jobs, setJobs] = useState<SimpleRow[]>([]), [companies, setCompanies] = useState<SimpleRow[]>([]);
  const [page, setPage] = useState(1), [query, setQuery] = useState(''), [priority, setPriority] = useState('الكل'), [sort, setSort] = useState('priority');
  const [selected, setSelected] = useState<SimpleRow | null>(null), [loading, setLoading] = useState(true), [notice, setNotice] = useState(''), [error, setError] = useState('');
  const [resolution, setResolution] = useState({ evidenceUrl:'', evidenceType:'Official Website', fact:'', contactName:'', title:'', email:'', phone:'', decisionMaker:false, confidence:'50', notes:'' });
  const load = async () => { setLoading(true); try { const [jobPage, companyPage] = await Promise.all([simpleCrud.page('agent_jobs', 1, 1000, { column:'status', value:'manual_research_required', order:'priority', ascending:false }), simpleCrud.page('companies', 1, 500, { order:'lead_score', ascending:false })]); setJobs(jobPage.rows); setCompanies(companyPage.rows); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر تحميل قائمة البحث.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const companyById = useMemo(() => new Map(companies.map((row) => [row.id,row])), [companies]);
  const filtered = useMemo(() => jobs.filter((job) => { const company=companyById.get(String(job.company_id)); const text=`${safe(company?.company_name)} ${safe(job.agent_name)} ${safe(job.last_error)}`.toLowerCase(); const rank=safe(company?.priority)||'C'; return (!query || text.includes(query.toLowerCase())) && (priority==='الكل'||rank===priority); }), [companyById,jobs,priority,query]);
  const grouped = useMemo(() => {
    const byCompany = new Map<string, SimpleRow[]>();
    filtered.forEach((job) => { const key=safe(job.company_id)||`general-${job.id}`; byCompany.set(key,[...(byCompany.get(key)??[]),job]); });
    return [...byCompany.entries()].map(([companyId,tasks])=>({companyId,tasks,job:tasks[0],company:companyById.get(companyId)})).sort((a,b)=>sort==='company'?safe(a.company?.company_name).localeCompare(safe(b.company?.company_name),'ar'):(safe(a.company?.priority)||'C').localeCompare(safe(b.company?.priority)||'C')||Number(b.company?.lead_score??0)-Number(a.company?.lead_score??0)||Number(a.company?.data_completeness??0)-Number(b.company?.data_completeness??0)||safe(a.job.created_at).localeCompare(safe(b.job.created_at)));
  },[companyById,filtered,sort]);
  const pageSize=25, totalPages=Math.max(1,Math.ceil(grouped.length/pageSize)), visible=grouped.slice((page-1)*pageSize,page*pageSize);
  const saveResolution = async (mode:'progress'|'resolved'|'unable') => {
    if (!selected) return;
    if (mode==='resolved' && !resolution.evidenceUrl.trim()) { setError('لا يمكن إنهاء المهمة دون رابط دليل.'); return; }
    if (mode==='unable' && !resolution.notes.trim()) { setError('أدخل سبباً واضحاً لتعذر التحقق.'); return; }
    setError('');
    try {
      await simpleCrud.update('agent_jobs', selected.id, { research_evidence_url:resolution.evidenceUrl, research_evidence_type:resolution.evidenceType, research_extracted_fact:resolution.fact, research_confidence:Number(resolution.confidence), research_notes:resolution.notes, research_resolution:mode==='unable'?'UNABLE_TO_VERIFY':mode==='resolved'?'RESOLVED':'IN_PROGRESS', ...(mode==='progress'?{}:{status:'completed',completed_at:new Date().toISOString()}) });
      if (mode==='resolved' && resolution.contactName.trim() && selected.company_id) await simpleCrud.create('contacts', { company_id:selected.company_id, company_name:safe(companyById.get(String(selected.company_id))?.company_name), full_name:resolution.contactName, name:resolution.contactName, position:resolution.title, email:resolution.email||null, mobile:resolution.phone, decision_maker:resolution.decisionMaker, contact_classification:resolution.decisionMaker?'Decision Maker':'General Contact', verification_status:resolution.decisionMaker?'VERIFIED':'PARTIALLY_VERIFIED', source_url:resolution.evidenceUrl, source:resolution.evidenceType, verified_at:resolution.decisionMaker?new Date().toISOString():null, confidence:Number(resolution.confidence), notes:resolution.notes });
      setNotice(mode==='progress'?'تم حفظ التقدم.':'تم إغلاق مهمة البحث مع حفظ الدليل.'); setSelected(null); await load();
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر حفظ نتيجة البحث.'); }
  };

  return <CRMPage title="البحث" description="مسار موحّد لاكتشاف الشركات واستكمال البيانات وحل مهام البحث اليدوي دون تشغيل أي مزود خارجي.">
    <div className="grid gap-3 sm:grid-cols-3"><div className="crm-card p-3"><span className="crm-chip status-success">البحث الداخلي · جاهز</span><p className="mt-2 text-xs text-[#75664d]">تصنيف وترتيب والتحقق من البيانات المحفوظة.</p></div><div className="crm-card p-3"><span className="crm-chip status-warning">البحث اليدوي · {jobs.length} مهمة</span><p className="mt-2 text-xs text-[#75664d]">يُحل بالدليل أو بسبب واضح لتعذر التحقق.</p></div><div className="crm-card p-3"><span className="crm-chip status-neutral">البحث الخارجي · متوقف</span><p className="mt-2 text-xs text-[#75664d]">ليس فشلاً للنظام ولا يعطل بقية العمل.</p></div></div>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-[#f7efdf] p-2">{tabs.map(([id,label])=><Link key={id} href={`/research?tab=${id}`} className={`shrink-0 rounded-xl px-4 py-2 text-sm font-bold ${tab===id?'bg-[#2f2417] text-white':'bg-white text-[#6f6044]'}`}>{label}</Link>)}</div>
    {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
    {tab==='discovery'&&<CompanyDiscoveryWorkspace/>}
    {tab==='enrichment'&&<section className="crm-card p-4"><h3 className="font-bold">الشركات التي تحتاج جهة اتصال</h3><p className="mt-1 text-sm text-[#75664d]">مرتبة حسب Priority ثم Lead Score. لا يتم تشغيل بحث خارجي من هذه الشاشة.</p><div className="mt-4 grid gap-2 md:grid-cols-2">{companies.filter(c=>safe(c.next_action).toLowerCase().includes('decision maker')).slice(0,50).map(c=><Link href={`/companies/${c.id}`} key={c.id} className="rounded-xl border bg-white p-3"><strong>{safe(c.company_name)}</strong><p className="text-xs text-[#75664d]">Priority {safe(c.priority)} · {safe(c.next_action)}</p></Link>)}</div></section>}
    {tab==='manual'&&<><div className="crm-card grid gap-2 p-3 md:grid-cols-4"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="بحث بالشركة أو المهمة" className="rounded-xl border p-2"/><select value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}} className="rounded-xl border p-2"><option>الكل</option><option>A</option><option>B</option><option>C</option></select><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border p-2"><option value="priority">الأولوية ثم النقص</option><option value="company">اسم الشركة</option></select><div className="rounded-xl bg-amber-50 p-2 text-center text-sm font-bold text-amber-800">{grouped.length} شركة · {filtered.length} مهمة محفوظة</div></div>{loading?<div className="crm-empty animate-pulse">جارٍ تحميل قائمة البحث…</div>:<div className="grid gap-2">{visible.map(item=><article key={item.companyId} className="crm-card grid gap-3 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong>{safe(item.company?.company_name)||'مهمة عامة'}</strong><span className="crm-chip status-warning">أولوية {safe(item.company?.priority)||'C'}</span><span className="crm-chip status-neutral">{item.tasks.length} مهام</span></div><p className="mt-1 text-xs text-[#75664d]">{[...new Set(item.tasks.map(job=>safe(job.agent_name)))].join('، ')} · البحث الخارجي متوقف ولا يعطل المعالجة الداخلية</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setSelected(item.job)} className="btn-primary">بحث يدوي</button>{item.company&&<Link href={`/companies/${item.company.id}`} className="btn-ghost">فتح الشركة</Link>}</div></article>)}</div>}<div className="flex items-center justify-between text-sm"><span>صفحة {page} من {totalPages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)} className="btn-ghost disabled:opacity-40">السابق</button><button disabled={page>=totalPages} onClick={()=>setPage(v=>v+1)} className="btn-ghost disabled:opacity-40">التالي</button></div></div></>}
    {selected&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-3"><div className="max-h-[92vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5"><h3 className="font-bold">حل مهمة البحث — {safe(companyById.get(String(selected.company_id))?.company_name)}</h3><p className="mt-1 text-xs text-[#75664d]">المطلوب: {safe(selected.last_error)||safe(selected.agent_name)}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={resolution.evidenceUrl} onChange={e=>setResolution({...resolution,evidenceUrl:e.target.value})} placeholder="Evidence URL *" className="rounded-xl border p-2"/><select value={resolution.evidenceType} onChange={e=>setResolution({...resolution,evidenceType:e.target.value})} className="rounded-xl border p-2"><option>Official Website</option><option>Vendor Portal</option><option>LinkedIn</option><option>Public Directory</option><option>Other</option></select><textarea value={resolution.fact} onChange={e=>setResolution({...resolution,fact:e.target.value})} placeholder="المعلومة المستخرجة" className="rounded-xl border p-2 md:col-span-2"/><input value={resolution.contactName} onChange={e=>setResolution({...resolution,contactName:e.target.value})} placeholder="اسم الشخص" className="rounded-xl border p-2"/><input value={resolution.title} onChange={e=>setResolution({...resolution,title:e.target.value})} placeholder="المنصب" className="rounded-xl border p-2"/><input value={resolution.email} onChange={e=>setResolution({...resolution,email:e.target.value})} placeholder="البريد" className="rounded-xl border p-2"/><input value={resolution.phone} onChange={e=>setResolution({...resolution,phone:e.target.value})} placeholder="الهاتف" className="rounded-xl border p-2"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={resolution.decisionMaker} onChange={e=>setResolution({...resolution,decisionMaker:e.target.checked})}/> صانع قرار</label><label className="text-sm">Confidence {resolution.confidence}%<input type="range" min="0" max="100" value={resolution.confidence} onChange={e=>setResolution({...resolution,confidence:e.target.value})} className="w-full"/></label><textarea value={resolution.notes} onChange={e=>setResolution({...resolution,notes:e.target.value})} placeholder="ملاحظات أو سبب تعذر التحقق" className="rounded-xl border p-2 md:col-span-2"/></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void saveResolution('progress')} className="rounded-xl border px-4 py-2">حفظ التقدم</button><button onClick={()=>void saveResolution('resolved')} className="rounded-xl bg-emerald-700 px-4 py-2 text-white">Resolve</button><button onClick={()=>void saveResolution('unable')} className="rounded-xl bg-amber-700 px-4 py-2 text-white">Unable to Verify</button><button onClick={()=>setSelected(null)} className="mr-auto rounded-xl border px-4 py-2">إلغاء</button></div></div></div>}
  </CRMPage>;
}
