'use client';

import { useEffect, useState } from 'react';
import { CRMPage } from '../../components/crm-shell';
import { simpleCrud, type SimpleRow } from '../../lib/supabase/simple-crud';

const today = new Date().toISOString().slice(0, 10);
const value = (item: SimpleRow, key: string) => String(item[key] ?? '');
const hasTavilyResult = (row: SimpleRow) => Boolean(row.data && typeof row.data === 'object' && 'tavily' in row.data);

export default function DashboardPage() {
  const [data, setData] = useState<Record<string, SimpleRow[]>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { void Promise.all(['companies', 'contacts', 'follow_ups', 'opportunities', 'meetings', 'messages', 'company_intelligence', 'agent_jobs'].map(async (table) => [table, await simpleCrud.list(table)] as const)).then((rows) => setData(Object.fromEntries(rows))).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  const companies = data.companies ?? [], contacts = data.contacts ?? [], followUps = data.follow_ups ?? [], opportunities = data.opportunities ?? [], meetings = data.meetings ?? [], messages = data.messages ?? [], intelligence = data.company_intelligence ?? [], agentJobs = data.agent_jobs ?? [];
  const ready = companies.filter((company) => ['A', 'B'].includes(value(company, 'priority')) && (company.general_email || company.email || company.general_phone || company.phone || contacts.some((contact) => contact.company_id === company.id))).length;
  const contacted = companies.filter((company) => company.outreach_status === 'Contacted' || company.last_contact).length;
  const responded = companies.filter((company) => company.last_outcome && !['No Response', ''].includes(value(company, 'last_outcome'))).length;
  const rfqs = opportunities.filter((opportunity) => value(opportunity, 'stage').includes('RFQ')).length;
  const metrics = [
    ['Enriched', intelligence.filter(hasTavilyResult).length], ['Needs Manual Research', agentJobs.filter((job) => job.status === 'manual_research_required').length], ['Queued', agentJobs.filter((job) => job.status === 'queued').length], ['Failed Jobs', agentJobs.filter((job) => job.status === 'failed').length],
    ['إجمالي الشركات', companies.length], ['Priority A', companies.filter((company) => company.priority === 'A').length], ['Priority B', companies.filter((company) => company.priority === 'B').length], ['Priority C', companies.filter((company) => company.priority === 'C').length],
    ['تحتاج استكمالاً', companies.filter((company) => ['Needs Enrichment', 'Poor Data'].includes(value(company, 'data_quality_status'))).length], ['صناع القرار', contacts.filter((contact) => contact.contact_classification === 'Decision Maker').length], ['روابط التسجيل', companies.filter((company) => company.vendor_registration_url).length], ['جاهزة للتواصل', ready],
    ['تم التواصل', contacted], ['ردود', responded], ['متابعات اليوم', followUps.filter((item) => value(item, 'date') === today && !['Completed', 'Cancelled'].includes(value(item, 'status'))).length], ['متأخرة', followUps.filter((item) => value(item, 'date') < today && !['Completed', 'Cancelled'].includes(value(item, 'status'))).length],
    ['اجتماعات', meetings.length], ['RFQs', rfqs], ['فرص مفتوحة', opportunities.filter((item) => !['Won', 'Lost'].includes(value(item, 'stage'))).length], ['فوز', opportunities.filter((item) => item.stage === 'Won').length],
  ];
  const top = [...companies].sort((a, b) => Number(b.lead_score ?? 0) - Number(a.lead_score ?? 0)).slice(0, 10);
  const funnel = [['الشركات', companies.length], ['جاهزة', ready], ['تم التواصل', contacted], ['ردود', responded], ['فرص', opportunities.length], ['RFQ', rfqs]];
  return <CRMPage title="لوحة القيادة التنفيذية" description="نظرة تشغيلية مباشرة على مسار تطوير الأعمال والبيانات الحقيقية من Supabase.">{error && <p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{loading ? <div className="crm-empty animate-pulse">جارٍ تحميل المؤشرات...</div> : <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, metric], index) => <div key={String(label)} className="crm-kpi"><div className="flex items-start justify-between"><p className="text-xs font-semibold text-[#75664d]">{label}</p><span className="text-lg text-[#b38b3c]">{['◆','◈','◷','!'][index % 4]}</span></div><p className="mt-3 text-3xl font-bold">{metric}</p></div>)}</div><div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><section className="crm-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#eadfc9] bg-[#faf5eb] p-4"><h3 className="font-bold">أفضل الشركات المستهدفة</h3><span className="crm-chip bg-[#f0e3ca] text-[#6d5125]">Top 10</span></div><div className="divide-y divide-[#eee3cd]">{top.map((company, index) => { const score = Math.max(0, Math.min(100, Number(company.lead_score ?? 0))); return <div key={company.id} className="grid gap-3 p-4 sm:grid-cols-[32px_1fr_150px] sm:items-center"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f5ecdc] text-xs font-bold">{index + 1}</span><div className="min-w-0"><p className="truncate font-semibold">{value(company, 'company_name')}</p><p className="mt-1 text-xs text-[#75664d]">{value(company, 'city')} · {value(company, 'company_type')}</p></div><div><div className="mb-1 flex justify-between text-xs"><span className={`crm-chip ${company.priority === 'A' ? 'bg-amber-100 text-amber-800' : 'bg-stone-100 text-stone-700'}`}>Priority {value(company, 'priority')}</span><strong>{score}/100</strong></div><div className="crm-progress"><span style={{ width: `${score}%` }} /></div></div></div>; })}</div></section><section className="crm-card p-4"><h3 className="font-bold">مسار التحويل</h3><div className="mt-4 space-y-4">{funnel.map(([label, count], index) => <div key={String(label)}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{count}</strong></div><div className="crm-progress"><span style={{ width: `${companies.length ? Math.max(3, Number(count) / companies.length * 100) : 0}%`, opacity: 1 - index * .08 }} /></div></div>)}</div><div className="mt-5 rounded-2xl bg-[#f8f1e4] p-4"><p className="text-xs text-[#75664d]">المسودات قيد المراجعة</p><strong className="mt-1 block text-2xl">{messages.filter((message) => ['Draft', 'Approved'].includes(value(message, 'status'))).length}</strong></div></section></div></>}</CRMPage>;
}
