export type ReadinessStatus='MISSING'|'IN_PROGRESS'|'COMPLETE';
export type ReadinessGroup='REGULATORY'|'TECHNICAL'|'FINANCIAL'|'PROOF'|'MARKETING';
export type ReadinessItem={id?:string;item_key:string;item_group:ReadinessGroup;label:string;weight:number;status:ReadinessStatus;document_url?:string;issued_at?:string|null;expires_at?:string|null;notes?:string};
export type Gateway={id?:string;gateway_key:string;name:string;required_keys:string[];status?:string;portal_url?:string;notes?:string};
export const GROUP_LABELS:Record<ReadinessGroup,string>={REGULATORY:'نظامي',TECHNICAL:'فني',FINANCIAL:'مالي',PROOF:'إثبات',MARKETING:'تسويقي'};
export const SEED_ITEMS:Omit<ReadinessItem,'status'>[]=[
{item_key:'cr',item_group:'REGULATORY',label:'السجل التجاري',weight:5},{item_key:'act',item_group:'REGULATORY',label:'نشاط المقاولات في السجل',weight:3},{item_key:'zakat',item_group:'REGULATORY',label:'شهادة الزكاة والضريبة',weight:3},{item_key:'gosi',item_group:'REGULATORY',label:'شهادة التأمينات الاجتماعية',weight:3},{item_key:'sca',item_group:'REGULATORY',label:'عضوية هيئة المقاولين',weight:6},{item_key:'grade',item_group:'REGULATORY',label:'شهادة تصنيف المقاولين',weight:8},{item_key:'iso9',item_group:'TECHNICAL',label:'ISO 9001',weight:6},{item_key:'iso14',item_group:'TECHNICAL',label:'ISO 14001',weight:3},{item_key:'iso45',item_group:'TECHNICAL',label:'ISO 45001',weight:6},{item_key:'hse',item_group:'TECHNICAL',label:'خطة HSE موثقة',weight:5},{item_key:'safe',item_group:'TECHNICAL',label:'مسؤول سلامة معتمد',weight:3},{item_key:'equip',item_group:'TECHNICAL',label:'قائمة المعدات والآليات',weight:3},{item_key:'fin',item_group:'FINANCIAL',label:'قوائم مالية مدققة (٣ سنوات)',weight:9},{item_key:'bank',item_group:'FINANCIAL',label:'تسهيلات بنكية',weight:4},{item_key:'bond',item_group:'FINANCIAL',label:'القدرة على خطاب ضمان',weight:3},{item_key:'proj',item_group:'PROOF',label:'مشاريع منفذة موثقة',weight:12},{item_key:'perf',item_group:'PROOF',label:'شهادات أداء من عملاء',weight:4},{item_key:'cv',item_group:'MARKETING',label:'سِيَر المهندسين الرئيسيين',weight:6},{item_key:'prof',item_group:'MARKETING',label:'الملف التعريفي للشركة',weight:6},{item_key:'value',item_group:'MARKETING',label:'العرض القيمي المكتوب',weight:2}];
export const SEED_GATEWAYS:Gateway[]=[
{gateway_key:'sub_main_contractor',name:'مقاولون رئيسيون — تسجيل مقاول باطن',required_keys:['cr','act','gosi','equip']},{gateway_key:'chamber_eastern',name:'غرفة الشرقية — دليل الأعضاء',required_keys:['cr']},{gateway_key:'muqawil',name:'منصة مقاول — هيئة المقاولين',required_keys:['cr','act']},{gateway_key:'modon',name:'مدن — موردو المصانع',required_keys:['cr','zakat','gosi','sca','equip']},{gateway_key:'etimad',name:'منصة اعتماد',required_keys:['cr','sca','grade','fin']},{gateway_key:'sec',name:'الشركة السعودية للكهرباء',required_keys:['sca','iso9','hse','fin']},{gateway_key:'developers',name:'مطورون عقاريون كبار',required_keys:['grade','proj','fin','iso9']},{gateway_key:'sabic',name:'سابك / عميل صناعي متقدم',required_keys:['iso9','iso45','hse','fin','proj']},{gateway_key:'ports_industrial',name:'موانئ والمدن الصناعية',required_keys:['sca','iso45','hse','safe']},{gateway_key:'aramco',name:'أرامكو',required_keys:['iso9','iso14','iso45','hse','safe','fin','proj','perf']}];
const v=(s:ReadinessStatus)=>s==='COMPLETE'?1:s==='IN_PROGRESS'?.5:0;
export const readinessScore=(a:ReadinessItem[])=>Math.round(a.reduce((s,i)=>s+i.weight*v(i.status),0)/(a.reduce((s,i)=>s+i.weight,0)||1)*100);
export const groupScore=(a:ReadinessItem[],g:ReadinessGroup)=>{const x=a.filter(i=>i.item_group===g),t=x.reduce((s,i)=>s+i.weight,0)||1;return{percent:Math.round(x.reduce((s,i)=>s+i.weight*v(i.status),0)/t*100),complete:x.filter(i=>i.status==='COMPLETE').length,total:x.length}};
export const missingFor=(g:Gateway,a:ReadinessItem[])=>g.required_keys.filter(k=>a.find(i=>i.item_key===k)?.status!=='COMPLETE');
export const gatewayState=(g:Gateway,a:ReadinessItem[])=>{const m=missingFor(g,a);return{missing:m,state:m.length===0?'OPEN':m.length===1?'ONE_AWAY':'LOCKED'} as const};
export function nextReadinessAction(a:ReadinessItem[],gs:Gateway[]){const o=a.filter(i=>i.status!=='COMPLETE');if(!o.length)return null;return o.map(item=>{const unlocks=gs.filter(g=>g.required_keys.includes(item.item_key)&&missingFor(g,a).length===1).length,nears=gs.filter(g=>g.required_keys.includes(item.item_key)&&missingFor(g,a).length<=2).length;return{item,unlocks,nears,score:unlocks*100+nears*10+item.weight}}).sort((x,y)=>y.score-x.score)[0]}
export function inferredGateway(c:{relationship_type?:unknown;required_gateway_key?:unknown;company_type?:unknown}){const e=String(c.required_gateway_key??'').trim();if(e)return e;const r=String(c.relationship_type??''),t=String(c.company_type??'').toLowerCase();if(r==='INFLUENCER_REFERRER')return'';if(r==='SUBCONTRACT_BUYER'||t.includes('contractor'))return'sub_main_contractor';if(t.includes('developer'))return'developers';if(t.includes('factory')||t.includes('industrial'))return'sabic';return'sub_main_contractor'}
export function commercialEligibility(c:{relationship_type?:unknown;required_gateway_key?:unknown;company_type?:unknown},a:ReadinessItem[],gs:Gateway[]){if(String(c.relationship_type??'')==='INFLUENCER_REFERRER')return{route:'relationship',percent:100,state:'RELATIONSHIP_ONLY' as const,missing:[],canBuildRelationship:true,canBid:false,reason:'قناة تأثير/إحالة؛ بناء العلاقة متاح دون تأهيل مسبق.'};const key=inferredGateway(c),g=gs.find(x=>x.gateway_key===key);if(!g)return{route:key||'direct',percent:100,state:'READY' as const,missing:[],canBuildRelationship:true,canBid:true,reason:'لا توجد بوابة محددة.'};const m=missingFor(g,a),pct=Math.round((g.required_keys.length-m.length)/Math.max(g.required_keys.length,1)*100);return{route:key,percent:pct,state:m.length===0?'READY' as const:m.length===1?'CONDITIONAL' as const:'BLOCKED' as const,missing:m,canBuildRelationship:true,canBid:m.length===0,reason:m.length===0?'متطلبات المسار مكتملة.':`يمكن بناء العلاقة الآن، لكن الدخول الرسمي/المناقصة يحتاج ${m.length} متطلب.`}}
export const expiringSoon=(a:ReadinessItem[],days=60)=>{const l=new Date(Date.now()+days*86400000).toISOString().slice(0,10);return a.filter(i=>i.expires_at&&i.expires_at<=l)};
