'use client';
/* eslint-disable @next/next/no-location-assign-relative-destination */
export const dynamic='force-dynamic';
import Link from 'next/link';
import { useEffect,useMemo,useRef,useState } from 'react';
import { CompanyActions } from '../../components/company-actions';
import { CompanyForm } from '../../components/company-form';
import { CRMPage } from '../../components/crm-shell';
import type { Company } from '../../lib/company-store';
import { companyOutreachState,isVerifiedDecisionMaker,type OutreachState } from '../../lib/domain/business';
import { supabaseCrm } from '../../lib/supabase/crm';
import { simpleCrud,type SimpleRow } from '../../lib/supabase/simple-crud';
import { CORE_SEGMENTS, SEGMENT_LABELS, companySegment } from '../../lib/presentation';
import type { TargetSegment } from '../../lib/intelligence/core';

const safe=(v:unknown)=>String(v??'').trim();
const stateLabel:Record<OutreachState,string>={CHANNEL_AVAILABLE:'قناة عامة فقط',CONTACT_NEEDED:'لم يتم العثور على الشخص الصحيح',DECISION_MAKER_VERIFIED:'صانع قرار موثق',DRAFT_READY:'مسودة جاهزة',APPROVED:'مسودة معتمدة',CONTACTED:'تم التواصل',REPLIED:'ورد رد'};
type View='all'|'a'|'missing-dm'|'ready'|'followup'|'opportunity';
type SegmentFilter='ALL'|TargetSegment;

export default function CompaniesPage(){
 const [companies,setCompanies]=useState<Company[]>([]),[related,setRelated]=useState<Record<string,SimpleRow[]>>({});
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [selected,setSelected]=useState<Set<string>>(()=>new Set()),[bulkBusy,setBulkBusy]=useState(false);
 const [query,setQuery]=useState(''),[view,setView]=useState<View>('all'),[segment,setSegment]=useState<SegmentFilter>('ALL'),[page,setPage]=useState(1),[editing,setEditing]=useState<Company|null>(null),[formOpen,setFormOpen]=useState(false);
 const handledEdit=useRef('');
 const load=async()=>{setLoading(true);setError('');try{const [rows,contacts,messages,events,followups,opps]=await Promise.all([supabaseCrm.companies.list(),simpleCrud.page('contacts',1,1000),simpleCrud.page('messages',1,1500),simpleCrud.page('communication_events',1,1500),simpleCrud.page('follow_ups',1,1000),simpleCrud.page('opportunities',1,1000)]);setCompanies(rows as Company[]);setRelated({contacts:contacts.rows,messages:messages.rows,events:events.rows,followups:followups.rows,opps:opps.rows})}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الشركات.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]); useEffect(()=>setPage(1),[query,view,segment]);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('view') as View|null;if(requested&&['all','a','missing-dm','ready','followup','opportunity'].includes(requested))setView(requested)},[]);
 useEffect(()=>{const editId=new URLSearchParams(window.location.search).get('edit')||'';if(!editId||handledEdit.current===editId||!companies.length)return;const target=companies.find(item=>item.id===editId);if(target){handledEdit.current=editId;setEditing(target);setFormOpen(true)}},[companies]);
 const states=useMemo(()=>new Map(companies.map(c=>[c.id,companyOutreachState({id:c.id,general_email:c.generalEmail,general_phone:c.generalPhone},related.contacts??[],related.messages??[],related.events??[])])),[companies,related]);
 const filtered=useMemo(()=>companies.filter(c=>!c.archivedAt).filter(c=>segment==='ALL'||companySegment({company_name:c.companyName,company_type:c.companyType,sector:c.sector,target_segment:c.targetSegment})===segment).filter(c=>`${c.companyName} ${c.sector} ${c.city}`.toLowerCase().includes(query.toLowerCase())).filter(c=>{const dm=(related.contacts??[]).some(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x)),state=states.get(c.id);if(view==='a')return c.priority==='A';if(view==='missing-dm')return !dm;if(view==='ready')return ['DECISION_MAKER_VERIFIED','DRAFT_READY','APPROVED'].includes(state??'');if(view==='followup')return (related.followups??[]).some(x=>x.company_id===c.id&&!['Completed','Cancelled'].includes(safe(x.status)));if(view==='opportunity')return (related.opps??[]).some(x=>x.company_id===c.id&&!['WON','LOST'].includes(safe(x.stage)));return true}).sort((a,b)=>(a.priority??'C').localeCompare(b.priority??'C')-(0)||(b.leadScore??0)-(a.leadScore??0)),[companies,query,related,segment,states,view]);
 const segmentCounts=useMemo(()=>new Map(CORE_SEGMENTS.map(id=>[id,companies.filter(c=>!c.archivedAt&&companySegment({company_name:c.companyName,company_type:c.companyType,sector:c.sector,target_segment:c.targetSegment})===id).length])),[companies]);
 const visible=filtered.slice((page-1)*25,page*25),pages=Math.max(1,Math.ceil(filtered.length/25));
 const save=async(c:Company)=>{try{if(editing){const overrideFields=(['priority','businessAngle','recommendedRole','recommendedLanguage','recommendedChannel','recommendedMessageStyle','nextAction','relationshipStage','doNotContact'] as const).filter(field=>editing[field]!==c[field]);const row=await supabaseCrm.companies.update(editing.id,{...c,humanOverride:overrideFields.length>0||c.humanOverride});if(overrideFields.length)await simpleCrud.create('audit_events',{company_id:editing.id,entity_type:'companies',entity_id:editing.id,action:'HUMAN_OVERRIDE',details:{fields:overrideFields,before:Object.fromEntries(overrideFields.map(field=>[field,editing[field]??null])),after:Object.fromEntries(overrideFields.map(field=>[field,c[field]??null]))}});setCompanies(items=>items.map(x=>x.id===editing.id?row as Company:x))}else{const row=await supabaseCrm.companies.create({...c,communicationHistory:[],followUps:[],opportunities:[]});setCompanies(items=>[row as Company,...items])}setFormOpen(false);setEditing(null);setNotice('تم حفظ الشركة بنجاح.')}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ الشركة.')}};
 const archive=async(c:Company)=>{if(!window.confirm('أرشفة الشركة مع الاحتفاظ بجميع بياناتها؟'))return;const row=await supabaseCrm.companies.update(c.id,{...c,archivedAt:new Date().toISOString()});setCompanies(items=>items.map(x=>x.id===c.id?row as Company:x));setNotice('تمت الأرشفة دون حذف البيانات.')};
 const toggleSelected=(id:string)=>setSelected(items=>{const next=new Set(items);if(next.has(id))next.delete(id);else next.add(id);return next});
 const visibleIds=visible.map(company=>company.id),allVisibleSelected=visibleIds.length>0&&visibleIds.every(id=>selected.has(id));
 const toggleAllVisible=()=>setSelected(items=>{const next=new Set(items);if(allVisibleSelected)visibleIds.forEach(id=>next.delete(id));else visibleIds.forEach(id=>next.add(id));return next});
 const bulkAccept=async()=>{const targets=companies.filter(company=>selected.has(company.id));if(!targets.length)return;setBulkBusy(true);setError('');try{const updated=await Promise.all(targets.map(company=>supabaseCrm.companies.update(company.id,{...company,status:'نشط'})));const byId=new Map(updated.map(company=>[company.id,company]));setCompanies(items=>items.map(company=>(byId.get(company.id) as Company|undefined)??company));setSelected(new Set());setNotice(`تم قبول ${targets.length} شركة وتعيين حالتها نشطة.`)}catch(e){setError(e instanceof Error?e.message:'تعذر قبول الشركات المحددة.')}finally{setBulkBusy(false)}};
 const bulkArchive=async()=>{const targets=companies.filter(company=>selected.has(company.id));if(!targets.length||!window.confirm(`أرشفة ${targets.length} شركة مع الاحتفاظ ببياناتها؟`))return;setBulkBusy(true);setError('');try{const archivedAt=new Date().toISOString();const updated=await Promise.all(targets.map(company=>supabaseCrm.companies.update(company.id,{...company,archivedAt})));const byId=new Map(updated.map(company=>[company.id,company]));setCompanies(items=>items.map(company=>(byId.get(company.id) as Company|undefined)??company));setSelected(new Set());setNotice(`تمت أرشفة ${targets.length} شركة دون فقد بياناتها.`)}catch(e){setError(e instanceof Error?e.message:'تعذرت أرشفة الشركات المحددة.')}finally{setBulkBusy(false)}};
 const bulkDelete=async()=>{const targets=companies.filter(company=>selected.has(company.id));if(!targets.length||!window.confirm(`حذف ${targets.length} شركة نهائيًا؟ سيؤدي ذلك إلى حذف البيانات المرتبطة بها ولا يمكن التراجع.`))return;setBulkBusy(true);setError('');try{await Promise.all(targets.map(company=>supabaseCrm.companies.remove(company.id)));setCompanies(items=>items.filter(company=>!selected.has(company.id)));setSelected(new Set());setNotice(`تم حذف ${targets.length} شركة نهائيًا.`)}catch(e){setError(e instanceof Error?e.message:'تعذر حذف الشركات المحددة.')}finally{setBulkBusy(false)}};
 return <CRMPage title="الشركات" description="الحسابات مفصولة حسب نوع العميل، ثم حسب أولوية الوصول والإجراء التجاري التالي." action={<div className="flex flex-wrap gap-2"><Link href={`/outreach?tab=strategy&segment=${segment}`} className="btn-secondary">إرسال بريد {segment==='ALL'?'للشركات':`— ${SEGMENT_LABELS[segment]}`}</Link><button onClick={()=>{setEditing(null);setFormOpen(true)}} className="btn-primary">إضافة شركة</button></div>}>
  {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}<button onClick={()=>void load()} className="mr-2 underline">إعادة المحاولة</button></div>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
  <section className="crm-card p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold text-[#9a742b]">ACCOUNT SEGMENTATION</p><h3 className="text-lg font-bold">الشركات حسب نوع العميل</h3><p className="text-xs text-[#75664d]">المطورون والاستشاريون والمقاولون والمصانع أصبحوا مسارات مستقلة قبل أي تواصل.</p></div><span className="crm-chip status-neutral">{companies.filter(c=>!c.archivedAt).length} حساب</span></div><div className="mt-3 flex gap-2 overflow-x-auto pb-2"><button onClick={()=>setSegment('ALL')} className={segment==='ALL'?'btn-primary shrink-0':'btn-ghost shrink-0'}>الكل <span className="crm-chip bg-white/20">{companies.filter(c=>!c.archivedAt).length}</span></button>{CORE_SEGMENTS.map(id=><button key={id} onClick={()=>setSegment(id)} className={segment===id?'btn-primary shrink-0':'btn-ghost shrink-0'}>{SEGMENT_LABELS[id]} <span className="crm-chip bg-white/20">{segmentCounts.get(id)||0}</span></button>)}</div></section>
  <div className="crm-card p-3"><div className="flex gap-2 overflow-x-auto pb-2">{([['all','كل الشركات'],['a','أولوية A'],['missing-dm','ينقصها صانع قرار'],['ready','جاهزة للتواصل'],['followup','تحتاج متابعة'],['opportunity','فرص مفتوحة']] as [View,string][]).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={view===id?'btn-primary shrink-0':'btn-ghost shrink-0'}>{label}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الشركة أو القطاع أو المدينة" className="mt-2 w-full rounded-xl border p-2.5"/></div>
  <div className="crm-card flex flex-wrap items-center gap-2 p-3"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={allVisibleSelected} onChange={toggleAllVisible} aria-label="تحديد كل الشركات الظاهرة" className="h-5 w-5"/>تحديد الكل في الصفحة</label><span className="crm-chip status-neutral">{selected.size} محدد</span><button disabled={!selected.size||bulkBusy} onClick={()=>void bulkAccept()} className="btn-primary">قبول المحدد</button><button disabled={!selected.size||bulkBusy} onClick={()=>void bulkArchive()} className="btn-secondary">أرشفة المحدد</button><button disabled={!selected.size||bulkBusy} onClick={()=>void bulkDelete()} className="btn-ghost text-red-700">حذف المحدد</button></div>
  {formOpen&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/45 p-3"><div className="max-h-[94vh] w-full max-w-5xl overflow-auto rounded-[28px] bg-white p-4 shadow-2xl"><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-bold text-[#9a742b]">{editing?'EDIT ACCOUNT':'NEW ACCOUNT'}</p><h3 className="text-lg font-bold">{editing?`تعديل ${editing.companyName}`:'إضافة شركة'}</h3></div><button onClick={()=>{setFormOpen(false);setEditing(null)}} className="btn-ghost">إغلاق</button></div><CompanyForm initialCompany={editing??undefined} submitLabel={editing?'حفظ التعديلات':'إضافة الشركة'} onSubmit={save} onCancel={()=>{setFormOpen(false);setEditing(null)}}/></div></div>}
  {loading?<div className="crm-empty animate-pulse">جارٍ تحميل الشركات…</div>:<>
   <div className="desktop-table overflow-hidden rounded-2xl border bg-white"><table className="w-full table-fixed text-right text-sm"><colgroup><col className="w-[5%]"/><col className="w-[22%]"/><col className="w-[13%]"/><col className="w-[10%]"/><col className="w-[18%]"/><col className="w-[32%]"/></colgroup><thead><tr className="bg-[#fbf7ef] text-[#795d28]"><th className="p-4"><input type="checkbox" checked={allVisibleSelected} onChange={toggleAllVisible} aria-label="تحديد كل الشركات الظاهرة" className="h-5 w-5"/></th><th className="p-4">الشركة</th><th className="p-4">نوع العميل</th><th className="p-4">الأولوية</th><th className="p-4">الوصول</th><th className="p-4">الإجراء التجاري التالي</th></tr></thead><tbody>{visible.map(c=>{const dm=(related.contacts??[]).find(x=>x.company_id===c.id&&isVerifiedDecisionMaker(x)),state=states.get(c.id)??'CONTACT_NEEDED';const seg=companySegment({company_name:c.companyName,company_type:c.companyType,sector:c.sector,target_segment:c.targetSegment});return <tr key={c.id} className="cursor-pointer border-t align-top hover:bg-[#fffaf0]" onClick={()=>location.assign(`/companies/${c.id}`)}><td className="p-4" onClick={event=>event.stopPropagation()}><input type="checkbox" checked={selected.has(c.id)} onChange={()=>toggleSelected(c.id)} aria-label={`تحديد ${c.companyName}`} className="h-5 w-5"/></td><td className="p-4"><span className="block text-[15px] font-bold leading-6">{c.companyName}</span><span className="mt-1 block text-xs text-[#75664d]">{c.sector||'قطاع غير محدد'} · {c.city||'مدينة غير محددة'}</span></td><td className="p-4"><span className="crm-chip status-neutral">{SEGMENT_LABELS[seg]}</span></td><td className="p-4"><span className="crm-chip status-warning">{c.priority||'C'}</span><span className="mt-2 block text-xs text-[#75664d]">Score {c.leadScore??0}</span></td><td className="p-4"><b className="block">{safe(dm?.full_name||dm?.name)||'الشخص الصحيح مطلوب'}</b><span className="mt-1 block text-xs text-[#75664d]">{stateLabel[state]}</span></td><td className="whitespace-normal break-words p-4 text-[14px] font-medium leading-7">{c.nextAction||'استكمال الملف وتحديد الإجراء التجاري التالي'}</td></tr>})}</tbody></table></div>
   <div className="mobile-cards grid gap-3">{visible.map(c=>{const seg=companySegment({company_name:c.companyName,company_type:c.companyType,sector:c.sector,target_segment:c.targetSegment});return <article key={c.id} className="crm-card p-4"><div className="mb-3 flex items-center gap-2"><input type="checkbox" checked={selected.has(c.id)} onChange={()=>toggleSelected(c.id)} aria-label={`تحديد ${c.companyName}`} className="h-5 w-5"/><span className="text-xs text-[#75664d]">تحديد الشركة</span></div><Link href={`/companies/${c.id}`} className="flex items-start justify-between"><div><strong>{c.companyName}</strong><p className="text-xs text-[#75664d]">{SEGMENT_LABELS[seg]} · {c.sector||'قطاع غير محدد'} · {c.city||'مدينة غير محددة'}</p></div><span className="crm-chip status-warning">أولوية {c.priority||'C'}</span></Link><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><p>Lead Score: <b>{c.leadScore??0}</b></p><p>الاكتمال: <b>{c.dataCompleteness??0}%</b></p></div><p className="mt-3 text-sm"><b>التواصل:</b> {stateLabel[states.get(c.id)??'CONTACT_NEEDED']}</p><p className="text-sm"><b>التالي:</b> {c.nextAction||'استكمال الملف'}</p><div className="mt-3"><CompanyActions companyId={c.id} archived={Boolean(c.archivedAt)} onEdit={()=>{setEditing(c);setFormOpen(true)}} onArchive={()=>void archive(c)}/></div></article>})}</div>
   {!visible.length&&<div className="crm-empty">لا توجد شركات مطابقة. غيّر نوع العميل أو الفلاتر.</div>}
   <div className="flex items-center justify-between text-sm"><span>{filtered.length} شركة · صفحة {page} من {pages}</span><div className="flex gap-2"><button className="btn-ghost" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>السابق</button><button className="btn-ghost" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>التالي</button></div></div>
  </>}
 </CRMPage>
}
