-- Phase 1.6 commercial focus: relationship types, referral attribution, legacy draft archive.
alter table public.companies add column if not exists relationship_type text not null default 'DIRECT_BUYER';
alter table public.companies drop constraint if exists companies_relationship_type_check;
alter table public.companies add constraint companies_relationship_type_check check (relationship_type in ('DIRECT_BUYER','SUBCONTRACT_BUYER','INFLUENCER_REFERRER','SUPPLY_SIDE','UNCLASSIFIED'));
create table if not exists public.referral_partners (id uuid primary key default gen_random_uuid(),owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,company_id uuid references public.companies(id) on delete set null,partner_name text not null,partner_type text not null check (partner_type in ('ENGINEERING_CONSULTANT','MAIN_CONTRACTOR_REFERRER','SUPPLIER_REFERRER','OTHER_REFERRER')),relationship_strength integer not null default 0 check (relationship_strength between 0 and 100),referrals_given integer not null default 0,last_touch_at timestamptz,notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.referrals (id uuid primary key default gen_random_uuid(),owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,partner_id uuid not null references public.referral_partners(id) on delete cascade,company_id uuid references public.companies(id) on delete set null,project_name text not null default '',status text not null default 'INTRODUCED' check (status in ('INTRODUCED','MEETING','RFQ','PROPOSAL','WON','LOST')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.referral_partners enable row level security; alter table public.referrals enable row level security; revoke all on public.referral_partners,public.referrals from anon; grant select,insert,update,delete on public.referral_partners,public.referrals to authenticated;
alter table public.opportunities add column if not exists source text not null default 'DIRECT';
alter table public.messages add column if not exists archived_at timestamptz; alter table public.messages add column if not exists archive_reason text not null default '';
